PyPDF2/filters.py
This is a port of ASCII85Decode to Python3. An issue this addresses is with pdf outputs from reportlab.
Relevant Py3 changes this addresses: http://python3porting.com/problems.html#bytes-strings-and-unicode
=> Python3 support for ASCII85Decode

PyPDF2/pdf.py
=> Python 3 compatibility with inline images

PyPDF2/pdf.py
Uses same structure as addLink
addURI
=> Added URI linking

PyPDF2/generic.py
Changes readStringFromStream to use a dict of escapes rather than a long if/else chain. (should lead to speed up, and looks cleaner)
=> speed up escape sequences

PyPDF2/pdf.py
i've been useing it and my files where only one line. That modification made my files to get the correct output.
=> Addition of line break for PDF line separators

PyPDF2/utils.py
Avoid string concatenation until after the loop.
=> Improve performance of RC4_encrypt in utils.py

setup.py
=> Fix broken link in setup script

tox.ini
=> add python 3.8 to tox.ini

PyPDF2/xmp.py
=> Fix simple typo: signifigance -> significance

Sample_Code/basic_features.py
Changed the print statement in line 7 to the python 3 print() function syntax for easy copy and past on modern machines.
=> Update print function to support python 3

MANIFEST.in, docs/conf.py, docs/index.rst, docs/modules/README.md, docs/user/README.md, docs/user/pdfcat.md, requirements/docs.in, requirements/docs.txt, setup.cfg
Also add pdfcat documentation:
https://pythonhosted.org/PyPDF2/Easy%20Concatenation%20Script.html
=> BUG/DOC: Add scripts back

Scripts/booklet.py
A script to create centerfold brochures/booklets, similar to bookletcreator.com.
=> Add Scripts/booklet.py.

PyPDF2/pdf.py
I have been using PyPDF2 for a long, and I had a couple of issues managing some kind of PDFs, I can attach an example if needed. What I have pushed in this Pull Request fixed my issues, and I thought it could be useful to share the code to improve the library. Here what I pushed:
- Using self.strict to raise the exception, it could be useful to keep the use of this for some kind of PDFs.
- If for some reason an object has None value we can't write anything to the stream, and it could happen with some PDFs.
=> Using self.strict and checking objects with None value

MANIFEST.in, setup.cfg
Only distribute it in the source
Closes #727
=> PKG: Make Tests not a subpackage

.github/workflows/unit-tests.yaml, PyPDF2/pagerange.py, README.md, docs/index.rst, setup.cfg
Also various links in setup.cfg
See #736
=> TST: Fix CI triggering (master ➔  main)

Resources/reportlab-inline-image.pdf, Tests/test_page.py
Credits to Sebastian Krause for creating the PDF:
https://github.com/py-pdf/PyPDF2/pull/331#issuecomment-1093783640
Preparation for PR #740
Co-authored-by: Sebastian Krause <sebastian@realpath.org>
=> TST: Add test for inline images

docs/index.rst, docs/user/adding-pdf-annotations.md, docs/user/reading-pdf-annotations.md
=> DOC: Working with annotations

PyPDF2/pdf.py
This doesn't solve the issue, but it might make it
less severe.
See #520
See #268
See https://github.com/virantha/pypdfocr/issues/59
Taken from https://github.com/sfneal/PyPDF3/commit/3558a69388b12bbf166d81b8a863b1d6c9843c62
Co-authored-by: danniesim <geemee@gmail.com>
=> ROB: Handle recursion error

PyPDF2/filters.py, PyPDF2/generic.py, PyPDF2/pdf.py, Tests/test_filters.py, Tests/test_papersizes.py
Full credit to
https://github.com/py-pdf/PyPDF2/pull/817/commits/9f628b3989b2f9714db9eb850bed323329a61922
who added the test in 2018 to PyPDF4
Co-authored-by: Acsor <nildexo@yandex.com>
=> TST: Add test for FlateDecode

PyPDF2/_reader.py
=> BUG: Incorrectly issued xref warning/exception

PyPDF2/_reader.py
=> BUG: _rebuild_xref_table expects trailer to be a dict

PyPDF2/filters.py
See https://github.com/py-pdf/PyPDF2/discussions/863
=> MAINT: Remove IronPython Fallback for zlib

PyPDF2/_reader.py, PyPDF2/_writer.py, PyPDF2/filters.py, PyPDF2/generic.py, PyPDF2/pagerange.py, PyPDF2/types.py, PyPDF2/utils.py, PyPDF2/xmp.py
some imports missed
also some local imports moved up
=> DEV : Complement relative imports

.github/workflows/github-ci.yaml, PyPDF2/_page.py
Backport of https://github.com/py-pdf/PyPDF2/pull/898/files
=> BUG: Fix PendingDeprecationWarning on _merge_page

PyPDF2/generic.py
It is included in the 1.x branch
=> DOC: Add missing deprecation warning for addChild

PyPDF2/_reader.py
This is one of the core methods that a lot of people use. It should not
be removed already.
=> BUG: Add getPage back

PyPDF2/xmp.py
=> DEV: Refine Any in xmp module

PyPDF2/_reader.py, tests/test_reader.py
=> ENH: Allow setting the decryption password in PdfReader.__init__

README.md
=> DOC: Remove reference to Scripts

PyPDF2/_reader.py
=> DOC: get_form_text_fields does not extract dropdown data

PyPDF2/_reader.py, PyPDF2/_utils.py, PyPDF2/_writer.py, tests/test_reader.py, tests/test_utils.py, tests/test_writer.py
=> ENH: Add writer.pdf_header property (getter and setter)

PyPDF2/_writer.py, tests/test_merger.py, tests/test_workflows.py
* Change UserWarning into PdfReadWarning
=> TST: Increase test coverage

tests/test_xmp.py
=> TST: Invalid XML in xmp information

docs/user/extract-text.md
=> DOC: OCR vs PDF text extraction

PyPDF2/_writer.py
=> MAINT: Use add_bookmark_destination in add_bookmark_dict

PyPDF2/_writer.py
Reduce code duplication
See #1098
=> MAINT: Use add_bookmark_destination in add_bookmark

PyPDF2/generic.py
Update type specification to be uniform for color property
=> correct color type

tests/test_reader.py
=> TST: Add MCVE showing outline title issue

tests/test_page.py
=> TST: Add xfail for decryption fail

PyPDF2/_reader.py
=> use `build_destination` for named destination outlines

tests/test_reader.py
test for #325
no issue to be solved
=> TST : add test for #325

PyPDF2/_reader.py, PyPDF2/_security.py, PyPDF2/_writer.py, tests/test_reader.py, tests/test_writer.py
* Killed 2340
* Killed 2341
* Killed 2342
* Killed 2383
See #1025
=> TST: Killing Security Mutants

tests/test_generic.py
The bold / italic flags don't work!
=> TST: Free-Text annotations

PyPDF2/_reader.py, tests/test_reader.py
=> ROB : cope with some corrupted entries in xref table

PyPDF2/_page.py, tests/test_page.py
will fix #1296
includes some customization capabilities to extend RTL
replaces #1305
=> ENH : auto detect RTL for text extraction

PyPDF2/generic/_base.py, tests/test_generic.py
=> ROB: Log errors during Float / NumberObject initialization

PyPDF2/_codecs/adobe_glyphs.py, tests/test_cmap.py
=> ROB: Accept '/annn' charset as ASCII code

PyPDF2/_cmap.py, tests/test_cmap.py
=> ROB: Cope with 2 digit codes in bfchar

PyPDF2/generic/_base.py, tests/test_generic.py
=> FIX : decode #23 in NameObject

PyPDF2/_page.py, tests/test_page.py
Context of this PR: https://github.com/py-pdf/PyPDF2/discussions/1333
=> ENH: Add PageObject.user_unit property

PyPDF2/_page.py, tests/test_page.py
=> ROB: Fix merge_page for pages without resources

PyPDF2/generic/_data_structures.py
Co-authored-by: 73272031+diavral@users.noreply.github.com
Fixes #1358
=> BUG: 'IndexError: index out of range' when using extract_text

PyPDF2/_reader.py, tests/test_reader.py
=> ENH: Add metadata.creation_date and modification_date

docs/user/extract-text.md
This PR contains two samples using visitor-functions when calling extract_text.
The first example may be of help in https://github.com/py-pdf/PyPDF2/discussions/1354.
The second one may be of help when debugging extract_text.
=> Docs text visitor

.github/SECURITY.md, .github/workflows/github-ci.yaml, README.md, docs/dev/deprecations.md, docs/dev/intro.md, docs/index.rst, docs/meta/project-governance.md
Just fixing a pet peeve of mine.
=> GitHub has a capital H

tests/test_reader.py
some temporary files where remaining at the end of the test
=> TST : cleanup temporary files

PyPDF2/generic/_data_structures.py, tests/test_generic.py
=> ROB : accept empty object as null objects

pypdf/_writer.py, tests/test_writer.py
=> BUG : upgrade clone_document_root

docs/user/extract-text.md
=> DOC: Missing semantic layer

pypdf/xmp.py
=> DOC: PDFX namespace

docs/dev/documentation.md
=> DOC: complete unfinished sentence

pypdf/_writer.py, tests/test_writer.py
=> ROB: Let PdfWriter.merge cope with missing "/Fields"

pypdf/generic/_data_structures.py, tests/test_workflows.py
=> ROB: Decode encoded values in get_fields

pypdf/_page.py, tests/test_page.py
=> BUG: Invalid font pointed during merge_resources

pypdf/_reader.py, tests/test_reader.py, tests/test_writer.py
=> ROB: Improve tolerance to invalid Names/Dests

pyproject.toml, tests/__init__.py, tests/test_generic.py, tests/test_merger.py, tests/test_page.py, tests/test_reader.py, tests/test_utils.py, tests/test_workflows.py, tests/test_writer.py
See https://stackoverflow.com/a/60086137/562769
=> STY: Use pathlib

tests/bench.py
=> MAINT: compress the writer page, not the reader page

tests/test_filters.py
=> TST: Add test for #1738

pypdf/constants.py, pypdf/generic/_annotations.py
BUG: /Flags should have been /F - typo. Was never released, though.
=> MAINT: Add AnnotationFlag

.pre-commit-config.yaml, pypdf/_security.py, pypdf/filters.py, pypdf/types.py, pypdf/xmp.py, pyproject.toml, requirements/ci-3.11.txt, tests/__init__.py
This automatically runs autofixes of ruff within the pre-commit hooks
=> DEV: ruff updates; activate --fix

docs/index.rst, docs/user/pdfa-compliance.md, tests/test_pdfa.py
Fixes #1739
https://pypdf--1807.org.readthedocs.build/en/1807/
=> DOC: PDF/A

pypdf/_protocols.py, pypdf/_writer.py, pypdf/generic/_base.py, pypdf/generic/_data_structures.py, pypdf/generic/_outline.py, pypdf/xmp.py, tests/test_generic.py, tests/test_protocols.py, tests/test_workflows.py
=> MAINT: Make encryption_key parameter of write_to_stream optional

pypdf/_encryption.py, pyproject.toml
* Rename parameters of Encrytpion class
* Add EncryptMetadata attribute
* Rename attribute key_size to Length
* Add P attribute explicitly instead of using "entry"
This makes #1816 smaller
=> MAINT: Refactor Encryption class

pypdf/_encryption.py, pyproject.toml
=> STY: Minor refactorings in _encryption.py

pypdf/filters.py, tests/test_filters.py
=> BUG : Cope with 1 bit images

docs/meta/comparisons.md
See https://pypdf--1827.org.readthedocs.build/en/1827/
=> DOC: Clarify that PyPDF2 is dead

pypdf/_page.py, tests/test_page.py
=> BUG: get_contents does not return ContentStream

pypdf/_writer.py, tests/test_writer.py
=> ENH: Simplify metadata input (Document Information Dictionary)

CONTRIBUTORS.md, docs/meta/comparisons.md
Added clarification for image conversion as per suggested in pull request #1837. And added a contributor for the same pull request.
=> DOC: Clarification of pdfplumbers image conversion capabilities

CHANGELOG.md, make_changelog.py
Also add missing part
See #1836
=> MAINT: Improve CHANGELOG generation script

pyproject.toml
=> MAINT: Add pytest-socket to pyproject.toml

tests/test_reader.py
=> MAINT: Parametrize test_named_destination

tests/bench.py
Check with
```
pytest tests/bench.py --benchmark-json output.json -vv
```
That command is [only run on `main`](https://github.com/py-pdf/pypdf/blob/main/.github/workflows/benchmark.yaml#L5)
=> BUG: Fix benchmark

docs/user/extract-text.md
Fix required arguments in visitor_text function.
=> DOC: text is the first argument of the visitor function

tests/test_workflows.py
=> TST: Increase coverage

docs/user/cropping-and-transforming.md
Feel free to close this and just include it in some other PR if you'd like. 😅 
Figured this is just as easy as opening an issue.
=> DOC: Fix typo in cropping-and-transforming.md

docs/user/encryption-decryption.md, pyproject.toml
=> DOC: Update notes on cryptography

pypdf/generic/_base.py, tests/test_generic.py
=> BUG: % to be hex encoded in names

pypdf/_writer.py, pypdf/filters.py, tests/test_filters.py
closes #1954
if anyone chan provide a 4bits test image it will be welcomed.
=> BUG: Process 2bits and 4bits images

.github/workflows/release.yaml
Get rid of the deprecation warning
=> DEV: Use softprops/action-gh-release@v1

.github/ISSUE_TEMPLATE/feature-request.md
Fixes a typo inside the feature request issue template.
=> STY: Fix typo in issue template

tests/test_generic.py, tests/test_page.py
Also: Remove a test which relied on external content that was deleted.
=> TST: Use test parametrization for reading text

tests/bench.py
For https://github.com/py-pdf/pypdf/pull/2068 :-)
=> TST: Add test_image_new_property benchmark

CONTRIBUTORS.md
=> DOC: Add Christian Clauss as a contributor

docs/index.rst, docs/meta/taking-ownership.md
This serves as an assurance to the community that pypdf will not die only if I become inactive.
Closes #2121
The built docs are here: https://pypdf--2123.org.readthedocs.build/en/2123/meta/taking-ownership.html
=> DOC: How to take ownership

pypdf/_reader.py, pypdf/_writer.py
=> DOC: Typos in ViewerPreferences docstrings

docs/meta/comparisons.md, docs/meta/scope-of-pypdf.md
See https://github.com/py-pdf/pypdf/discussions/2171#discussioncomment-6956195
=> DOC: Cross-link pdfly

pypdf/_page.py, tests/test_page.py
=> BUG: getcontents() shall return None if contents is NullObject

pypdf/_page.py, tests/test_page.py
=> BUG: Merge pages without resources

pypdf/filters.py, tests/test_filters.py
=> BUG: Cope with indirect objects in filters and remove deprecated code

CONTRIBUTORS.md, docs/index.rst, docs/user/viewer-preferences.md, pypdf/_writer.py, pypdf/generic/_viewerpref.py, tests/test_writer.py
Add documentation and fix a method name as discussed in #2105
=> MAINT: Rename PdfWriter.create_viewer_preferences to PdfWriter.create_viewer_preferences

docs/conf.py
=> DOC: Update copyright footer in docs

pypdf/_page.py, tests/test_images.py
no issue raised. detected during #2214 dev
=> BUG: images property fails if NullObject in list

tests/test_writer.py
Full credit to sjoerdjob for this contribution via #1995
See #1788
=> TST: Regression test against non-deterministic accidental object reuse

pypdf/_writer.py
https://github.com/py-pdf/pypdf/pull/2003
=> STY: File identifier generation restructuring

pypdf/_writer.py
See https://github.com/py-pdf/pypdf/pull/2003
Co-authored-by: exiledkingcc <exiledkingcc@gmail.com>
=> DOC: Quote specs in generate_file_identifiers

CONTRIBUTORS.md
I have tried to improve the formatting of the contributors page. Additionally, I have added myself to the list.
=> DOC: Improve formatting of contributors page

.github/scripts/check_pr_title.py, .github/workflows/github-ci.yaml
=> DEV: Ensure that the PR titles have the correct format

.github/dependabot.yml
See https://github.com/py-pdf/pypdf/pull/2414#issuecomment-1897968843.
=> DEV: Make dependabot aware of our PR prefixes

docs/user/metadata.md
Document how to overwrite some file metadata, while keeping other values.
=> DOC: Document easier way to update metadata

pypdf/_page.py, tests/test_page.py
=> ROB: missing basefont entry in type 3 font

tests/test_page.py
Fixes #2157 by addressing https://github.com/py-pdf/pypdf/issues/2157#issuecomment-1712744267
=> TST: Improve test_get_contents_from_nullobject to show real use-case

docs/user/encryption-decryption.md
See https://github.com/py-pdf/pypdf/issues/2543
If you clone the document instead of manually copying each page; you don't break attachments, links, layers, ...
=> DOC: encryption/decryption: clone document instead of copying all pages

pypdf/filters.py, tests/test_images.py
=> BUG: Process CMYK images without a filter correctly

tests/test_page_labels.py
fix some issues when getting file from remove server
=> TST: fix download issues from #2562

.github/workflows/create-github-release.yaml, .github/workflows/publish-to-pypi.yaml, .github/workflows/release.yaml
This should make it easier to manually fix things if a workflow does not work. It also makes the Github Action(s) easier to read.
=> DEV: Different workflows for git tag / PyPI / GH Release Page

docs/user/file-size.md, docs/user/metadata.md, docs/user/suppress-warnings.md
file-size.md: simplify examples
metadata.md: add two fields
suppress-warnings.md: small wording change
=> DOC: Improve examples

docs/user/suppress-warnings.md
Have exceptions, warnings, and log messages in a consistent order
=> DOC: Make ordering consistent

pypdf/constants.py
Add fields to PageLayouts and CatalogDictionary.
Also reorder to match the PDF 2.0 table order.
=> DOC: Add some references to ISO 32000-2:2020 (PDF 2.0)

tests/test_reader.py
Server is down for some times blocking commits
=> TST: Test doc unreachable

docs/user/metadata.md, pypdf/_page.py
Also make metadata examples more concise
=> DOC: Slightly improve the wording of PageObject

docs/user/pdf-version-support.md, docs/user/robustness.md, pypdf/_writer.py, pypdf/constants.py, pypdf/generic/_data_structures.py
=> DOC: Update PDF standard references

pypdf/_doc_common.py, pypdf/_page_labels.py, pypdf/_writer.py, pypdf/constants.py
Also remove superfluous parenthesis around LAST_MODIFIED, in PageAttributes (constants.py).
=> DOC: Improve slightly some docstrings and comments

tests/bench.py
closes https://github.com/py-pdf/pypdf/pull/2675#issuecomment-2133284545
=> BUG: fix bench after #2675

tests/bench.py
hoping it will be good this time
=> BUG: fix benchmark 2

CONTRIBUTING.md, CONTRIBUTORS.md, docs/user/adding-pdf-annotations.md, pypdf/generic/__init__.py
Please close #2689, this is the replacement for the first commit therein.
=> DOC: Improve docstrings

docs/user/extract-images.md, docs/user/merging-pdfs.md, docs/user/viewer-preferences.md, pypdf/_doc_common.py, pypdf/_encryption.py, pypdf/_writer.py, pypdf/filters.py
=> DOC: Added that threads can now contain a metadata stream

pypdf/_page.py, pypdf/generic/_fit.py, pypdf/pagerange.py
Also, tiny changes to pagerange.py and _fit.py
=> DOC: Improve comments in the PageObject class

docs/dev/testing.md
=> DOC: Remove references to tox from docs

pypdf/annotations/__init__.py, pypdf/annotations/_base.py
Plus tiny change of a comment.
=> STY: Reorder exported symbols

pypdf/annotations/_markup_annotations.py
=> STY: Remove boolean value comparison

.github/workflows/github-ci.yaml
Starting 2024-09-02, hidden files are ignored by default: https://redirect.github.com/actions/upload-artifact/issues/602
=> DEV: Fix coverage uploads

pypdf/_writer.py, pypdf/generic/_base.py, pypdf/generic/_data_structures.py, tests/test_generic.py, tests/test_writer.py
allow to load hudge files
closes #2839
=> ENH: add full parameter to PdfWriter constructor

pypdf/_codecs/_codecs.py
Just a few refinements :innocent:
=> STY: Code reuse within LzwCodec.encode

.flake8
=> DEV: Remove .flake8

.github/workflows/github-ci.yaml
Python 3.13.0 was released on October 7, 2024.
=> DEV: Change 3.13-dev to 3.13

pypdf/_writer.py
Functions insert_blank_page and _pdf_objectify.
=> STY: Tiny refactor

pypdf/_utils.py
Move them above where they are first used.
=> STY: Move whitespace definitions

pypdf/generic/_outline.py
Change deprecate_no_replacement to deprecation_no_replacement.
=> DEP: Update to deprecation_no_replacement

docs/user/reading-pdf-annotations.md
Variable used is 'annot' and not 'annotation'; update to reflect this.
=> DOC: Correct example

docs/user/file-size.md
This gives more ideas for reducing PDF file size.
=> DOC: Add link to a presentation

pypdf/_writer.py
Small changes to comments and docstrings in class PdfWriter.
=> DOC: Tweak comments and docstrings

pypdf/annotations/_base.py
The annotations Polygon and PolyLine automatically set /Rect.
=> DOC: Add Polygon to a comment

pypdf/generic/_base.py
Use f-strings in two methods of class PdfObject.
=> STY: Use f-strings

pypdf/_writer.py
Add two comments to the __init__ of PdfWriter.
=> DOC: More comments in PdfWriter

pypdf/__init__.py
=> STY: Modify f-string

pypdf/generic/_data_structures.py, tests/test_images.py
=> BUG: Handle chained colorspace for inline images when no filter is set

docs/modules/PdfDocCommon.md, docs/modules/PdfDocCommon.rst
=> DOC: Fix documentation for PdfDocCommon

tests/test_page.py
=> STY: Simplify a test

pypdf/_reader.py, pypdf/_utils.py
Also tweak comment in skip_over_whitespace.
=> STY: Initialize variable extra using skip_over_whitespace

pypdf/errors.py
Specifically "PyPDF" to "pypdf".
=> MAINT: Change two words in comments

pypdf/filters.py
The filters have been reordered to match the order in ISO 32000-2:2020.
=> STY: Small refactor of decode_stream_data

pyproject.toml, tests/test_page.py, tests/test_reader.py
TD004 is a missing colon in TODO.
=> DEV: Remove TD004 from ignored Ruff rules

pypdf/_text_extraction/_layout_mode/_fixed_width_page.py, tests/test_text_extraction.py
=> BUG: Handle further Tf operators in text extraction layout mode

pypdf/_page.py
=> MAINT: Fix formatting of warning message and include exception message

pypdf/_text_extraction/_layout_mode/_fixed_width_page.py, tests/test_text_extraction.py
=> ROB: Handle zero height fonts when extracting text

.github/workflows/github-ci.yaml, pypdf/_doc_common.py, tests/test_doc_common.py
=> ENH: Support alternative (U)F names for embedded file retrieval

pypdf/_page.py
Mainly in comments to increase readability.
=> MAINT: Tiny change to _extract_text

pypdf/generic/_data_structures.py, pyproject.toml
PLR1714 is consider merging multiple comparisons.
=> DEV: Remove ignoring Ruff rule PLR1714

pypdf/_utils.py, setup.cfg
ANN202: Missing return type annotation for private function.
=> DEV: Remove ignore Ruff rule ANN202

pyproject.toml
D203: incorrect-blank-line-before-class.
=> DEV: Remove ignore Ruff rule D203

pyproject.toml
D407: missing dashed underline after section.
=> DEV: Remove ignore Ruff rule D407

docs/modules/PdfDocCommon.rst, docs/user/extract-attachments.md, pypdf/_doc_common.py, pypdf/generic/__init__.py, pypdf/generic/_files.py, tests/generic/test_files.py, tests/test_doc_common.py
=> ENH: Handle attachments in /Kids and provide object-oriented API

pypdf/_codecs/adobe_glyphs.py
Unnecessary for dict modification.
=> STY: Remove global statement

pypdf/_reader.py, tests/test_reader.py
=> ROB: Avoid negative seek values when reading partially broken files

pypdf/_writer.py, pypdf/generic/_data_structures.py, pypdf/generic/_image_inline.py, pypdf/generic/_utils.py, pyproject.toml
RET507: Unnecessary "else"  or "elif" after "continue" statement.
=> DEV: Remove excluding Ruff rule RET507

pypdf/_doc_common.py, pypdf/_reader.py, pypdf/filters.py, pypdf/generic/_data_structures.py, pypdf/pagerange.py, pyproject.toml
RET506: Unnecessary "else" or "elif" after "raise" statement.
=> DEV: Remove ignore Ruff rule RET506

pypdf/_cmap.py, pypdf/_codecs/_codecs.py, pypdf/_page.py, pypdf/annotations/_markup_annotations.py, pypdf/generic/_base.py, pyproject.toml, tests/__init__.py, tests/test_page.py
RET504: Unnecessary assignment before return statement.
=> DEV: Remove ignore Ruff rule RET504

pyproject.toml
ARG003: Unused class method argument.
=> DEV: Remove ignore Ruff rule ARG003

pyproject.toml
D400: First line should end with a period.
=> DEV: Remove ignore Ruff rule D400

pyproject.toml, tests/test_text_extraction.py, tests/test_workflows.py, tests/test_writer.py
UP031: Use format specifiers instead of percent format.
=> DEV: Remove ignore Ruff rule UP031

pypdf/_cmap.py, pypdf/_doc_common.py, pypdf/_page.py, pypdf/_page_labels.py, pypdf/_text_extraction/__init__.py, pypdf/_utils.py, pypdf/_writer.py, pypdf/generic/_base.py, pypdf/generic/_data_structures.py, pypdf/generic/_utils.py, pyproject.toml, tests/test_encryption.py, tests/test_page.py, tests/test_reader.py
RET505: Unnecessary "else" after "return" statement.
=> DEV: Remove ignore Ruff rule RET505

tests/test_text_extraction.py
Slight changes, including removal of comments about previous values.
=> MAINT: Change comments

pypdf/_cmap.py
=> STY: Remove slicing

pypdf/generic/_base.py, tests/test_generic.py
=> ENH: Add support for IndirectObject.__iter__

pyproject.toml
Make project.optional-dependencies section more readable. Also remove "if 0:" from exclude_lines.
=> DEV: Tweak pyproject.toml

pypdf/filters.py, tests/test_filters.py
=> ROB: Attempt to deal with non-rectangular FlateDecode streams

pypdf/_writer.py, tests/test_writer.py
=> ROB: Fix compression issues for removed images which might be None

pypdf/_writer.py
The Metadata key was added in PDF 2.0.
=> DOC: Update thread information

pypdf/generic/_data_structures.py
Variable NumberSigns is unused. Also tweak some comments.
=> MAINT: Remove an unused variable and zero from the start of slices

pypdf/_page.py
Add underscore for readability: _translate_value_inline_image.
=> MAINT: Rename _translate_value_inlineimage

pypdf/constants.py
Also sort some other constants to be the same as their order in tables in the specification.
=> MAINT: Add structure destination to GoToActionArguments

pypdf/_page.py
Also amend two bound checks to be consistent within _page.py.
=> STY: Use list comprehension

pypdf/_page.py, pypdf/_reader.py
Including removing some backup commented code.
=> MAINT: Tweak comments

pypdf/_doc_common.py, pypdf/generic/_base.py, tests/test_doc_common.py
=> BUG: Add missing named destinations being ByteStringObjects

pypdf/generic/_image_inline.py
For RunLengthDecode, a length value of 128 shall denote EOD.
=> MAINT: Change inline image comments

.pre-commit-config.yaml, pypdf/_cmap.py, pypdf/_doc_common.py, pypdf/_page.py, pypdf/_reader.py, pypdf/_writer.py, pypdf/_xobj_image_helpers.py, pypdf/generic/_data_structures.py, pypdf/generic/_viewerpref.py, pypdf/xmp.py, requirements/ci-3.11.txt, requirements/ci.txt, tests/test_doc_common.py
=> STY: Update to mypy 1.16.0

pypdf/_writer.py, tests/test_writer.py
=> ROB: Deal with annotations not being lists on merge

docs/user/installation.md, pyproject.toml
=> DEP: Drop Python 3.8 support
