- PyPDF2/generic.py
I have recently been getting "Unexpected escaped string" for some PDFs. Unfortunately I can't share this PDFs but adding the hash sign to the list of escape sequences fixes the problem.
I believe this was the sequence causing the exception in my pdf `<< /Type /OCG /Name (1318-A-121\ SiteTrees\#1_Pen_No__1)`
> Add hash (#) to list of odd escape sequences

- PyPDF2/generic.py
This specific case I found was a document with a BaseFont named 'ABCDEE+\xef\xbc\xad\xef\xbc\xb3#20\xe6\x98\x8e\xe6\x9c\x9d'
> Catch for UnicodeEncodeError in NameObject

- PyPDF2/pdf.py
Workaround for PDFs which behave as if decrypted, though were 
encrypted without a password.
This occasional bug dates back to here: https://bugs.launchpad.net/pypdf/+bug/355479 
Basically the PDFs have been encrypted incorrectly and for most purposes invisibly (other applications used to handle these PDFs have built-in exception and don't require explicit decryption with no password), so this tends to cause bad user experience in trying to work out this PyPDF2 bug.
In my case it was bank-generated bank statements that otherwise behave as unencrypted, no password is required to view or manipulate them, it was only be caught by PyPDF2. This workaround allows PyPDF2 to do batch processing of these types of files without borking on every one.
Non encrypted PDFs aren't affected.
> Fix "file has not been decrypted" error #51.

- PyPDF2/filters.py
Fixing an issue when there is not data to decode:
- In some cases the data to decode using the method `filters.decodeStreamData` is an empty string, I think that in those cases we shouldn't try to decode the data.
> Fix decode stream data issue

- CHANGELOG
- PyPDF2/generic.py
Some PDF returned value greater than size of long, therefore Overflow error in generic.py, This leads to Overflow exception, OverflowError:python int too large to convert to C long
Example PDF here for review, https://www.dropbox.com/s/eibno2yoornalxg/Drawing%20deadman%20anchor.pdf?dl=0
> Overflow error in generic.py

- PyPDF2/merger.py
- PyPDF2/pagerange.py
- PyPDF2/pdf.py
- PyPDF2/utils.py
Fixes issue https://github.com/mstamy2/PyPDF2/issues/178
- Adding functions isString(), isInt(), isBytes() to make type testing simpler and more consistent. Works for Python 2 and 3.
- Note: "string_type", "bytes_type" and "int_types" are functionally unchanged: Made sure all references to these types were compatible with how things worked pre-fork.
> utils.py changes

- PyPDF2/pdf.py
Each "TJ" entry is a separate piece of text so provide some way for the user to separate them in the extracted text. This way the user can then txt.split("\n") to get a list of all text blocks
> Separate extracted text fields with EOLs

- PyPDF2/filters.py
After investigating an odd error:
`NotImplementedError: unsupported filter /Fl`
I saw the PDF had this line:
`<</Filter/Fl/First 12/Length 828/N 2/Type/ObjStm>>stream`
But most objects had:
`<</Size 306/Filter/FlateDecode/Length 947/Type/XRef/W[1 3 1]`
After looking at the filters.py file, I saw the short-names were not added. After modifying the filters.py, the code is up and running again.
A thanks to Matthew Weiss for helping with this as well.
> Add abbreviated short-names for filters

- PyPDF2/merger.py
We are concatenating PDFs from users and ran into an issue with one of them being encrypted. Following the advice from #51, we used `decrypt` and got a `PdfFileReader` working. However, we were unable to merge in the decrypted PDF to `PdfFileMerger` as it creates a new object which loses the decryption key.
In order to keep things simple and not mutate any underlying streams, we decided to copy over the `_decryption_key` upon merge. In this PR:
- Added `_decryption_key` copying to `PdfFileReader` clone in `PdfFileMerger`
> Added decryption key copying for PdfFileMerger

- PyPDF2/generic.py
Fix a bug which could result in a "Stream has ended unexpectedly" error being raised unnecessarily if a Name object runs right up against the end of a file stream.
I have a test case, but it's unfortunately very convoluted and will be quite difficult for me to get running in PyPDF. However, if one could somehow make a PDF with a inline stream object, and a Name object at the very end of the stream, then it would trigger this bug fix (not sure how to do that).
> Fix "Stream has ended unexpectedly" for Name Objects

- PyPDF2/pdf.py
- Tests/tests.py
According to the PDF doc, an entry in the document's name dictionary,
listing the JavaScript actions, is required to execute parameterized
function call.
Also note that:
> The names are arbitrary and need not bear any relation to the
> JavaScript name
> space.
In this case, the name is a random string (using uuid).
> Parameterized JavaScript.

- PyPDF2/pdf.py
This is a simple fix to ignore errors caused by xref table indexing if self.strict set to False.
> Ignore xref table zero index error if self.strict = False

- .gitignore
- PyPDF2/pdf.py
This is fix for https://github.com/mstamy2/PyPDF2/issues/176
I have a document for which it is possible to reproduce the issue but it is copyrighted so I haven't included it in unittests. I can provide the document on demand. Seems that the bug involves .eps vector images.
> Pageobject.mergePage() fails for some pages with images (Python3)

- PyPDF2/generic.py
- PyPDF2/pdf.py
_readInlineImage fails for any image that has "EIQ" inside of it.
In the in function `_readInlineImage`, we were looking for the operation `EI` and `Q`.  However, we were not checking to ensure that there was whitespace between `EI` and `Q`. Accordingly, any image that had `EIQ` in its ascii encoded data would trigger the end of the image, and cause errors.
This fix changes that.
Also, added a small nit change to remove extraneous zeros from our output formatting. These can needlessly bloat the size of the PDF and hurt readability.
> Fix a bug in _readInlineImage

- PyPDF2/filters.py
- PyPDF2/utils.py
Added support for missing PNG filter algorithms: Average (type 3) and Paeth (type 4).
For more on the filters: https://www.w3.org/TR/PNG-Filters.html
> Add support for PNG filters average and paeth

- PyPDF2/merger.py
The previous check was always evaluated to False on Python 3, which led to generating blank pages in output PDF. I replaced it with a duck-typing check compatible with Python 2 and 3.
The issue has been described here: https://github.com/mstamy2/PyPDF2/issues/293
> Fix PdfFileMerger for file objects on Python 3.

- PyPDF2/pdf.py
update _rotate function to account for /Rotate being set to an IndirectObject instead of an int
> Fix issue #337 - Rotate PDF fails if /Rotate is set to an IndirectObject

- PyPDF2/pdf.py
I encountered a PDF that would error out on a PdfReadError. Only raising the errors/assertions when `strict=True` allowed the pdf to generate successfully. I don't truly understand the implications of the error being raised/assertion.
> Relax assertions when strict is False

- README.md
README is lacking installation instructions. This should help.
> pip install instructions added

- PyPDF2/utils.py
formatWarning does fail if the filename does not contain a path.
You can reproduce this with:
```
from PyPDF2.utils import formatWarning
formatWarning('message', DeprecationWarning, 'filename', 100)
```
> Fix formatWarning for filename without slash

- PyPDF2/pdf.py
**Previously the function `.extractText()` reads the text in the PDF and returns without any spaces.
In this fix the pdf.py file has been modified to add " " (space) in between two words**
_Here is an example below:_-
**Original Sentence :** `"The quick brown fox jumps over the lazy dog"`
**Previous Output :** `"Thequickbrownfoxjumpsoverthelazydog"`
**Output After fix :**` "The quick brown fox jumps over the lazy dog"`
> Fixed extractText()-Not returning text with spaces

- PyPDF2/generic.py
This happens when the library is used with `-Werror`, since `\c` is not a valid Python escape sequence.
> Fix "invalid escape sequence" SyntaxError

- PyPDF2/pdf.py
The default value of sys.stderr will be None in this case, so care should be taken to avoid causing an AttributeError when trying to show an otherwise nonfatal warning.
> Fix: Avoid error when printing warning in pythonw

- PyPDF2/generic.py
The constructor expects the page argument to be a reference to a page (`IndirectObject`), rather than the integer index of the page in the document. This change updates the docs for the class.
Also, my editor removed a couple of trailing spaces. Let me know and I'll remove those changes if you'd rather they weren't included here.
> Updated docstring for Destination class

- PyPDF2/pdf.py
Good python code practice suggest
avoid constructions such as range(len(x)).
> Code refactoring

- PyPDF2/pdf.py
Appeared when merging PDFs that have
content-stream-inline images
This patch was provided by Georg Graf :
https://github.com/mstamy2/PyPDF2/issues/196#issuecomment-172829990
Thank you!
Closes #196
> BUG: Stream operations can be List or Dict

- .github/workflows/unit-tests.yaml
- Tests/test_workflows.py
Similar to #667, while we are still publishing 1.x releases, good to have testing. Once move to work for 2.0, I would suggest branching the current `master` into a long lived `1.x` branch, and then can remove this test stuff as 2.0 will drop python2 support.
> TST: Test Python 2.7

- tox.ini
pytest command copied from github workflow
> make tox use pytest and add more Python versions

- Tests/test_writer.py
Without this fix, running the test suite on Windows results in:
`FAILED Tests/test_writer.py::test_remove_images - PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'dont_commit_writer_removed_image.pdf'`
> in test_writer.py, make sure tmp file is closed before removing it

- PyPDF2/filters.py
BUG: Off-by-one
FIX: Set 2**32-1 inclusive
Closes #312
Credits to Michael Sander (speedplane) who
included it here:
https://github.com/py-pdf/PyPDF2/pull/333
> BUG: Fix ASCII85Decode.decode assertion

- PyPDF2/filters.py
- Scripts/pdf-image-extractor.py
- Tests/test_reader.py
BUG: Two tests with the same name existed
> TST: Fix test_get_images

- PyPDF2/pagerange.py
I have no clue why it can be None, but it aparently can be None.
Closes #737
> BUG: Guard formatting of __init__.__doc__ string

- PyPDF2/pdf.py
The header being read by `readObjectHeader` has the format:
<idnum> <generation> obj
where `<idnum>` and `<generation>` are integers.
Previously an arbitrary number of spaces was being allowed between `<idnum>` and `<generation>`, but not between `<generation>` and `obj`.
With this pull request an arbitrary number of spaces between `<generation>` and `obj` is allowed (but raises a warning similarly to how other extraneous whitespace is handled) .
> readObjectHeader: Allow extra whitespace before "obj"

- PyPDF2/pdf.py
> When merging pages together, clip by trimBox, which would otherwise be ignored

- PyPDF2/merger.py
- PyPDF2/pdf.py
Hello, I've added the capability to chose if you want to overwrite the default warning as a flag in the PdfFileMerger.
That was causing problems with SQLAlchemy.
> Add overwriteWarnings logging capabilities to PdfFileMerger.

- Tests/test_basic_features.py
- Tests/test_pagerange.py
- Tests/test_reader.py
- Tests/test_utils.py
- Tests/test_writer.py
Doing so somethings shows that not the error message you've
expected is thrown, but another one of the same Exception type
> TST: Check Error messages

- PyPDF2/pdf.py
"New" features that we use:
* PEP-343: with statements (Python 2.5+)
* PEP-389: argparse (Python 2.7+; just in Scripts)
* https://bugs.python.org/issue2335 : Set literals
* https://bugs.python.org/issue2333 : Dictionary / set comprehensions
* ...
Python 2.6 had its last security update in 2013 - 9 years ago.
I'm sure people have long moved on.
The package is also marked as Python 2.7+ and CI only runs for
Python 2.7 and 3.6+.
For this reason, I will not make a major version bump.
> DEP: Remove Python 2.6 and older support

- PyPDF2/filters.py
- PyPDF2/generic.py
- PyPDF2/merger.py
- PyPDF2/pdf.py
- PyPDF2/utils.py
- Tests/test_merger.py
I hope this makes them easier to understand / extend
> MAINT: Split long functions

- PyPDF2/utils.py
> BUG: Import exceptions from PyPDF2.errors in PyPDF2.utils

- PyPDF2/generic.py
Users report the following error:
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
and:
InvalidOperation: Invalid Literal for Decimal '0.0000-74251147'
Ghostscript when it encounters this reference, treats the value as if it
was "0.0". PyPDF2 will now do the same.
Closes #386
Co-authored-by: James Campbell <james@supmenow.com>
> ROB: Invalid float object; use 0 as fallback

- PyPDF2/pdf.py
- Tests/test_writer.py
> BUG: 'PdfFileWriter' object has no attribute 'stream'

- PyPDF2/pdf.py
- Tests/test_writer.py
Closes #574
Closes #801
Co-authored-by: Craig Jones <craig@k6nnl.com>
> ENH: Allow setting field flags for forms

- PyPDF2/pdf.py
> ENH: Allow setting permission flags when encrypting

- PyPDF2/pdf.py
- Tests/test_reader.py
When trying to find the xref marker, the PDF reader code the file backwards and builds a so called line by concatenating strings in a loop.
This leads to O(n^2) performance. For files where the xref marker can not be found at the end this takes a enormous amount of time:
1mb of zeros at the end: 45.54 seconds
2mb of zeros at the end: 357.04 seconds
(measured on a laptop made in 2015)
This pull request changes the relevant section of the code to become O(n), leading to a run time of less then 1 second for both cases mentioned above. Furthermore this PR adds a test to prevent regression.
Unit tests have been run manually on Python 2.7.18 and Python 3.8.10.
> fix pdf reader getting stuck when trying to read large files wihhout xref marker

- PyPDF2/xmp.py
- Tests/test_xmp.py
Fix: Convert decimal to int before passing it to datetime
Closes #774
> BUG: TypeError in xmp._converter_date

- PyPDF2/pdf.py
- Tests/test_papersizes.py
- Tests/test_reader.py
> MAINT: Validate PDF magic byte in strict mode

- .github/workflows/github-ci.yaml
- PyPDF2/filters.py
- Tests/test_filters.py
- pytest.ini
Full Credit goes to https://github.com/py-pdf/PyPDF2/pull/817/commits/5c74416e6cb9675628975f12528ca908c554bb63
who did this in 2018 for PyPDF4
Co-authored-by: Acsor <nildexo@yandex.com>
> TST: Add test for filters.ASCIIHexDecode

- PyPDF2/filters.py
- Tests/test_filters.py
Full credit to
https://github.com/py-pdf/PyPDF2/pull/817/commits/6dc90b1e64c1965b61aa2561ce912f64ca19cad4
Co-authored-by: Acsor <nildexo@yandex.com>
> TST: Add Test for ASCII85Decode

- PyPDF2/filters.py
I have no idea how to test for that in GithubActions.
As this likely only affects a small fraction of PyPDF2 users,
I want to ignore it for now.
Feel free to add a PR that adds IronPython to GithubActions -
then we can enable this again.
> DEV: Ignore IronPython parts for code coverage

- PyPDF2/pdf.py
- Tests/test_reader.py
Proposal for #297
Issue is due to corrupted startxref pointer and/or xref table
Fixed proposed if incorrect pointer look for all objs to rebuild an xref table
Tests updated
> Fix #297 : fix corruption in startxref or xref table

- PyPDF2/pdf.py
- Tests/test_reader.py
This refactoring aims at making maintenance easier:
1. Too long functions make it hard to grasp the overall behavior. Hence the `_get_xref_issues` function was split out
2. `_get_xref_issues` is made a static method of the PdfFileReader to show that it belongs to the reader, but doesn't require any of its attributes
3.  `_get_xref_issues` makes use of an integer return value instead of raising + catching exceptions. That also seems easier to grasp for me. Also, capturing exceptions is a tiny bit more expensive than just returning an int
4. `_rebuild_xref_table` was moved to a method for the same reason.
> MAINT: Small refactoring after #788

- PyPDF2/_reader.py
- Tests/test_reader.py
#604 
root cause: probably extraction from a document not extracting properly destination
changes:
getDestinationPageNumber return -1 with NullObject
in case of Strict = False, return a destination to first page to prevent error (no change in case of Strict=True)
note ; warning generated
Test added with the sample test
(duplicate of  #821 to match refactoring)
> fix  issues with  missing destinations (#604)

- PyPDF2/_reader.py
- PyPDF2/filters.py
- PyPDF2/generic.py
- PyPDF2/pdf.py
- Tests/test_filters.py
- Tests/test_generic.py
- Tests/test_reader.py
* BUG: Changed default /K to conform with the PDF 1.7 standard
* TST: Add test for CCITTFax
* TST: Add test for TextStringObject
STY:
* Group Python 2.7 imports
* camelCase variables to snake_case
* Apply black formatter
> MAINT: Separated CCITTFax param parsing/decoding

- CHANGELOG
- PyPDF2/_reader.py
- PyPDF2/merger.py
- PyPDF2/utils.py
- tests/test_writer.py
PdfFileReader and PdfFileMerger no longer have the `overwriteWarnings`.
The new behavior is `overwriteWarnings=False`.
Additionally, PyPDF2.utils.formatWarning was removed
> DEP: overwriteWarnings parameter of reader/merger

- PyPDF2/_reader.py
- PyPDF2/merger.py
- tests/test_reader.py
It's expected that this is a more sensible default for most users.
> Change default to strict=False in PdfFileReader/PdfFileMerger

- .github/ISSUE_TEMPLATE/bug-report.md
- .pre-commit-config.yaml
- PyPDF2/_page.py
- PyPDF2/_reader.py
- PyPDF2/_security.py
- PyPDF2/_writer.py
- PyPDF2/filters.py
- PyPDF2/generic.py
- PyPDF2/merger.py
- PyPDF2/pagerange.py
- PyPDF2/papersizes.py
- PyPDF2/utils.py
- PyPDF2/xmp.py
- make_changelog.py
- setup.py
- tests/test_filters.py
- tests/test_generic.py
- tests/test_utils.py
- tests/test_workflows.py
- tests/test_xmp.py
As support for Python 3.5 and lower was dropped, we can use more modern syntax
Add pyupgrade to pre-commit hooks
> MAINT: Use Python 3.6 language features

- PyPDF2/_merger.py
- PyPDF2/filters.py
- PyPDF2/generic.py
> Remove star imports

- PyPDF2/filters.py
This PR removes the nested imports from `PyPDF2.generic` in `PyPDF2.filters` as there's already a top-level import on that module for the typing information and so having additional nested imports provides no benefit at the cost of clutter. Additionally, one of the nested imports was for something that was already being imported at that top level.
> MAINT: Remove unnecessary generics imports

- PyPDF2/filters.py
This ports over a791ef16c009bcf528fba2e566cc58b5d18dc4f4 from `main` to `2.0.0-dev`, while retaining the type annotations that had been previously added in `2.0.0-dev`.
> MAINT: Remove IronPython Fallback for zlib 

- PyPDF2/merger.py
tracked in
https://github.com/mvicenzi/pdf_tools/issues/2
as said in title
> BUG : Merger to be initialize with strict=False default

- PyPDF2/_reader.py
- PyPDF2/_writer.py
- PyPDF2/merger.py
This PR removes a handful of places where `warnings` module was being double imported (once at the top-level and once within a method), leaving in place just the top-level import.
> MAINT: Remove duplicate warnings imports

- PyPDF2/_reader.py
- PyPDF2/_utils.py
- PyPDF2/_writer.py
- PyPDF2/merger.py
- PyPDF2/pagerange.py
Fixes #886
PR fixes a bug where the codebase was internally relying on deprecated functions and so would trigger the warnings even though there's no action the user could meaningful taken. Now, the internal usage relies on an internal version of the function that executes as before sans deprecation warning while leaving in place a user facing version of the function that has the deprecation warning (and relies on the new internal function to keep behavior consistent).
> BUG: Incorrectly show deprecation warnings on internal usage

- PyPDF2/_page.py
- tests/test_basic_features.py
PR fixes a PendingDeprecationWarning that was raised when you attempted to merge or transform a PageObject as it referenced the old camel-case version of the method instead of using the property.
Note: This PR can be backported (hopefully as-is) to 1.x branch.,
> BUG: Fix PendingDeprecationWarning on merge/transform PageObject

- PyPDF2/_reader.py
- tests/bench.py
- tests/test_merger.py
- tests/test_reader.py
PR fixes a bug where a deprecation UserWarning would be raised when fetching outlines on a reader where an outline has a sub-outline.
Additionally, I also modified all tests to also use `get_outlines` instead of `getOutlines`.
As an aside, should `get_outlines` similar be deprecated and push users to the `outlines` property instead? Feels weird to have both `reader.outlines` and `reader.get_outlines()` and they do the same thing and that violates the "Zen of Python".
Also, 1.x branch already has these changes done already.
> BUG: Fix UserWarning on reading outlines

- PyPDF2/_reader.py
- tests/test_basic_features.py
- tests/test_reader.py
PR update the test suite so that the `convert_to_int` function is principally tested instead of `convertToInt`. I've also added another test case for `convert_to_int` that minimally covers the happy path, as well as a test that `convertToInt` does raise a pending deprecation warning.
I moved the tests from `tests/test_basic_features.py` to `tests/test_reader.py` as these methods are not part of the public API, and so I think makes more sense to be in the test file for the module they live in.
> TST: Improve tests for convert_to_int

- PyPDF2/_merger.py
- PyPDF2/_page.py
- PyPDF2/_reader.py
- PyPDF2/_writer.py
- PyPDF2/filters.py
- PyPDF2/generic.py
- PyPDF2/xmp.py
- README.md
- docs/modules/DocumentInformation.rst
- docs/user/adding-pdf-annotations.md
- docs/user/cropping-and-transforming.md
- docs/user/file-size.md
- docs/user/forms.md
- docs/user/reading-pdf-annotations.md
- tests/bench.py
- tests/test_basic_features.py
- tests/test_generic.py
- tests/test_merger.py
- tests/test_page.py
- tests/test_reader.py
- tests/test_workflows.py
- tests/test_writer.py
- tests/test_xmp.py
PyPDF2 interface changes:
* getXmpMetadata / xmpMetadata ➔ xmp_metadata
* get_outlines ➔ _get_outlines (use outlines property instead)
* getXmpMetadata ➔ xmp_metadata
* getDestArray ➔ dest_array
* additionalActions ➔ additional_actions
* defaultValue ➔ default_value
* mappingName ➔ mapping_name
* altName ➔ alternate_name
* fieldType ➔ field_type
* ensureIsNumber ➔ _ensure_is_number
* decodedSelf : decoded_self
* addChild / removeChild  ➔ add_child / remove_child
* flateEncode  ➔ flate_encode
* getData / setData  ➔ get_data / set_data
DOC: Use the new PyPDF2 interface
STY: Use reader/writer as variable names for PdfReader / PdfWriter
> DEP: PEP8 renaming

- .github/workflows/github-ci.yaml
We needed it because we were manipulating a docstring programmatically.
As long as we don't rely on assert / docstrings being present, we don't
need to test with -OO.
> TST: Remove -OO testrun from CI

- PyPDF2/_page.py
- tests/test_page.py
PR fixes a bug where calling `pageObject.add_transformation()` on a page that doesn't have the optional `/Contents` value would cause an error to be raised:
```
>>> pageObject.add_transformation(None)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/mpeveler/github/PyPDF2/PyPDF2/_page.py", line 932, in add_transformation
self[NameObject(PG.CONTENTS)] = content
File "/home/mpeveler/github/PyPDF2/PyPDF2/generic.py", line 666, in __setitem__
raise ValueError("value must be PdfObject")
ValueError: value must be PdfObject
```
The fix here is to only try to update the `/Contents` attribute only if we actually have an updated contents value, which ignores the case where `/Contents` does not exist.
> BUG: Fix error adding transformation to page without /Contents

- PyPDF2/xmp.py
Fixes #914 (though will want to backport)
PR fixes a bug where some methods in the `xmp` module were referencing the old name of internal functions (`_getText`) instead of the new version (`_get_text`). 
I suppose this would be an argument to move to only supporting Python 3.7 so that can use forward references for type annotations, so that could do `self: XmpInformation` throughout these to allow mypy to help catch these sorts of errors.
> BUG: Fix XmpInformation missing method _getText

- PyPDF2/xmp.py
Closes #914
Credits to MasterOdin for:
https://github.com/py-pdf/PyPDF2/pull/915
> BUG: XmpInformation missing method _getText

- PyPDF2/_page.py
- PyPDF2/_utils.py
- docs/user/cropping-and-transforming.md
- tests/test_basic_features.py
- tests/test_page.py
Closes #896
This adds a `rotate` method to `PageObject` to be used instead of `rotate_clockwise`, which is now marked as deprecated. The intent here is that given that there's going to be only one method to rotate the `PdfObject` in the future, there's not much point in having it be suffixed with the direction as the direction can just be documented, and then save everyone some keystrokes in usage.
As an aside, wasn't really sure what "type" to give this PR, whether it should be `DEP`, `ENH`, `MAINT` or some other one. 🤷
> ENH: Add rotate method for PageObject

- PyPDF2/__init__.py
- PyPDF2/_page.py
- PyPDF2/_reader.py
- PyPDF2/_utils.py
- PyPDF2/_writer.py
- PyPDF2/generic.py
- PyPDF2/xmp.py
- tests/test_reader.py
We are trying to break as few running systems as possible. For this
reason we keep the adapter methods / classes in PyPDF2 until 3.0.0.
This commit is done to not confuse people. It will not be backported
to the 1.x branch though.
> DOC: Adjust deprecation messages

- PyPDF2/_page.py
- resources/crazyones.txt
Full credit to pubpub-zz who introduced this change in
https://github.com/py-pdf/PyPDF2/pull/881
Co-authored-by: pubpub-zz <4083478+pubpub-zz@users.noreply.github.com>
> ENH: Improve space setting for text extraction

- CHANGELOG
This PR updates the CHANGELOG entries for `1.25.1`, `1.27.1`, `1.27.2`, and `1.27.3` patches such that they're shown above the minor release, and that they match the style of later `1.27` and `1.28` patch releases.
> DOC: Fix style of 1.25 and 1.27 patch notes

- PyPDF2/_merger.py
- PyPDF2/_page.py
- PyPDF2/_reader.py
- PyPDF2/_utils.py
- PyPDF2/_writer.py
- PyPDF2/generic.py
- PyPDF2/xmp.py
PR updates all deprecation warnings in the codebase to go through two wrapper functions, to make it easy to keep the message unified, ensure proper `stacklevel` used, and that the same type of warning is raised, overall ensuring we're not doing a lot of repeating ourselves. All three of those were different in various places across the codebase, leading to a bit of a confusing experience. The wrapper functions were originally accidentally added in #913, though were unused till now.
> MAINT: Add wrapper function for PendingDeprecationWarnings

- PyPDF2/generic.py
Under some conditions, the 'if self.decodedSelf' implicit expression
evaluates to 'False' incorrectly.
For example, d = None and d = {} both evaulated to 'False', but in the
updated code only the evaluation of `if d is None` is correct.
> corrected the null evaluation of decoded stream objects.

- .github/workflows/github-ci.yaml
Closes (hopefull) #748.
Untested, as would require credentials.
Uses:
https://github.com/softprops/action-gh-release
https://github.com/softprops/action-gh-release
Note that I personally use semantic-release in everything (in ci), which handles the releasing/tags/pypi etc all in one with decent changelogs.  But this is (hopefully) what was requested.
> ci: release to pypi and github on tagged pushes.

- PyPDF2/_merger.py
- PyPDF2/_page.py
- PyPDF2/_reader.py
- PyPDF2/_writer.py
- PyPDF2/generic.py
- PyPDF2/xmp.py
This allows us to track the blind spots of our unit tests better
> DEV: Mark deprecated code with no-cover

- tests/bench.py
Ignore the PdfReadWarning here as this is only supposed to be used
for performance testing.
> TST: Ignore PdfReadWarning in benchmark

- PyPDF2/__init__.py
Currently, accessing the `PageObject.create_blank_page` static method depends on importing `PageObject` with something like `from PyPDF2._page import PageObject`. It feels weird as the leading underscore indicates that the `_page` module should not be imported directly.
This PR adds `PageObject` to `__init__.py` allowing it to be imported in a cleaner way with `from PyPDF2 import PageObject`.
> Add `PageObject` to __init__.py

- PyPDF2/_reader.py
- PyPDF2/_utils.py
- tests/test_reader.py
- tests/test_utils.py
This function (which reads the previous line in a binary stream) is pretty inefficient when handling long lines - if the stream is a buffered binary stream, each one-byte "backwards" read may trigger a full buffer read, and (more significantly) iteratively building the line we want to return is quadratic in its total length.
> Optimize read_next_end_line

- PyPDF2/_writer.py
Issue: When creating files with the current PpdfWriter,
Adobe Acrobat asks 'would you like to save this file'
when attempting to close it - although no changes were made.
Fix: Remove 'self.set_need_appearances_writer()' from writers
`__init__` function
Closes #963
> BUG: Adobe Acrobat 'Would you like to save this file?'

- PyPDF2/_reader.py
- PyPDF2/_security.py
- PyPDF2/_utils.py
- PyPDF2/generic.py
Function calls are cheap, but not for free in Python.
The b_ function converts a string to a bytes object. When we have
a constant string, we can use the constant byte representation
instead (a b"byte literal" instead of b_("string literal"))
> PI: Remove b_ calls

- PyPDF2/generic.py
Now that we have Python 3, we have bytes always at this point. This means the `ord_` call is no longer necessary.
For #68 this should result in ~4% less work as 291 Million calls to this function are NOT made.
> PI: Remove ord_ calls

- README.md
- docs/user/encryption-decryption.md
- docs/user/installation.md
This PR updates the docs to make mention of the `PyPDF2[crypto]` extras package when interacting with AES encrypted PDFs.
> DOC: add mention of crypto extra_requires for install

- Makefile
- PyPDF2/generic.py
- mutmut-test.sh
- tests/test_writer.py
Relates to https://github.com/davidhalter/parso/issues/207
> DEV: Adjust string formatting to be able to use mutmut

- PyPDF2/_merger.py
- PyPDF2/_writer.py
- tests/test_merger.py
Closes #968 (introduced with #339)
> BUG: Fix missing page for bookmark

- PyPDF2/_merger.py
- PyPDF2/generic.py
- tests/test_generic.py
Issue: An
AttributeError: 'NoneType' object has no attribute 'get_object'
was raised when trying to write a page that was merged.
Fix: Guard IndirectObject.get_object access
Closes #997
> ROB: Deal with invalid Destinations

- PyPDF2/_writer.py
- PyPDF2/generic.py
PdfFileWriter._sweepIndirectReferences checks if object is already in pdf.
This check will reduce file-size significantly when merge pdfs and there are same objects, for example images.
> PI: Check duplicate objects in writer._sweep_indirect_references

- PyPDF2/_encryption.py
- PyPDF2/_merger.py
- PyPDF2/_page.py
- PyPDF2/_reader.py
- PyPDF2/_security.py
- PyPDF2/_utils.py
- PyPDF2/_writer.py
- PyPDF2/constants.py
- PyPDF2/errors.py
- PyPDF2/filters.py
- PyPDF2/generic.py
- PyPDF2/pagerange.py
- PyPDF2/xmp.py
* `rtype` was removed in most cases. It makes sense sometimes, but only if it is not exactly what the type annotation is
* No newlines after the function docstring
* Keep lines under 80 characters. It's mostly not an issue for docstrings.
See PEP-257 for some guides.
flake8-naming was used to find those spots.
> STY: Docstring formatting

- tox.ini
For example, run only one test in py39 env using an option -k:
$ tox -e py39 -- -k test_issue585
For example, run only one test in all envs using an option -k:
$ tox -- -k test_issue585
> Added {posargs} to tox.ini for adding options from a command line.

- tests/test_reader.py
The `Path` constructor allows a variable amount of arguments to it which it joins together similar to `os.path.join` works, so it's not necessary to use `os.path.join` before passing the args to `Path`.
REPL example:
```
>>> os.path.join(RESOURCES_PATH, 'crazyones.pdf')
'/Users/mpeveler/code/github/PyPDF2/resources/crazyones.pdf'
>>> Path(os.path.join(RESOURCES_PATH, 'crazyones.pdf'))
PosixPath('/Users/mpeveler/code/github/PyPDF2/resources/crazyones.pdf')
>>> Path(RESOURCES_PATH, 'crazyones.pdf')
PosixPath('/Users/mpeveler/code/github/PyPDF2/resources/crazyones.pdf')
```
> TST: Simplify pathlib PdfReader test

- PyPDF2/_reader.py
Example to resolve IndirectObject when it refers to a free entry.
This could resolve issues #1034 and #521 .
> Resolve IndirectObject when it refers to a free entry.

- PyPDF2/_reader.py
> ROB: Guard against None-value in _get_outlines

- PyPDF2/_page.py
- PyPDF2/generic.py
> BUG: Let Page.scale also scale the crop-/trim-/bleed-/artbox

- PyPDF2/_page.py
Closes #1021
Co-authored-by: probel_hero <93727145+SXHRYU@users.noreply.github.com>
> MAINT: Annotate angle parameter of page.rotate with int instead of float

- docs/user/add-watermark.md
> DOC: Watermark and stamp

- PyPDF2/_reader.py
- PyPDF2/generic.py
- tests/test_reader.py
> ENH: Add color and font format to returned outline

- PyPDF2/_cmap.py
The code within the if block assumes that lst has index 0 and index 1.
So the predicate should depend on lst having at least two elements.
This resolves the error I described at
https://github.com/py-pdf/PyPDF2/issues/1091#issuecomment-1184718747
(I'm not sure that it would resolve the other issue raised by
@MartinThoma)
> _cmap.py: avoid IndexError in parse_to_unicode

- PyPDF2/generic.py
> Check if pdf variable is None

- PyPDF2/_page.py
In issue #1102 adobe reader/acrobat doesn't like if same page is referred more than one time
> Prevent deduplication of PageObject

- tests/test_page.py
> TST: Add xfail test for IndexError when extracting text

- PyPDF2/_cmap.py
- PyPDF2/_page.py
This is not a principled fix, but it is a hack to avoid a crash when
encountering an empty dstString in a `beginbfchar` table in a
ToUnicode CMap.
The right way to fix this would be to replace all the string
manipulation with a formal grammar, but i don't have the skill or
capacity to do that right now.
Instead, we take narrow aim at the issue of zero-length (empty) hex
string representations.
We take advantage of the fact that no angle-bracket-delimited hex
string contains a . character.  when we encounter an empty hex string,
rather than replacing it with the empty string, we replace it with a
literal ".".  Then, when we encounter a ".", we remember that it was
supposed to be an empty string.
One consequence of this fix is that the exported cmap can now return
an empty string, so we …
> Avoid a crash when a ToUnicode CMap has an empty dstString in beginbfchar

- PyPDF2/_cmap.py
- PyPDF2/_page.py
Credits to pubpub-zz, see
https://github.com/py-pdf/PyPDF2/pull/1118#issuecomment-1186148575
Co-authored-by: pubpub-zz <4083478+pubpub-zz@users.noreply.github.com>
> MAINT: Text extraction improvements

- PyPDF2/_reader.py
- PyPDF2/generic.py
- tests/test_reader.py
Enables retrieval of "/Count" attribute of outline item in PdfReader by implementing property `outline_count`. Addresses #1122
> ENH: add `outline_count` property

- CONTRIBUTORS.md
- docs/conf.py
- docs/index.rst
Discussions: https://github.com/py-pdf/PyPDF2/discussions/798
> DOC: Contributors file

- docs/meta/project-governance.md
- tests/test_reader.py
- tests/test_writer.py
There are small typos in:
- docs/meta/project-governance.md
- tests/test_reader.py
- tests/test_writer.py
Fixes:
- Should read `inducing` rather than `indiducing`.
- Should read `decisions` rather than `decisons`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: Fix a few typos

- PyPDF2/_reader.py
- tests/test_reader.py
rebuild the xref if the parent chained xref is invalid
> ROB : cope with invalid parent xref (#1089)

- PyPDF2/_cmap.py
- tests/test_page.py
robustness issue identified in #1134
> ROB: cope with missing /W entry (#1134)

- PyPDF2/generic.py
Closes #1138 
The `EncodedStreamObject` class was missing the deprecated `getData` and `setData` functions, which would call the `get_data` and `set_data` functions respectively after issuing a deprecation warning. The original functions were totally renamed in https://github.com/py-pdf/PyPDF2/commit/c774ab0cbc82c99a7dcbaa3260b6c4545f1b3659. That same commit did properly handle the `getData` and `setData` functions in the `DecodedStreamObject` though, where they issue a deprecation warning and then call `get_data` and `set_data`.
This should probably be backported to 1.x where it exists as well, as it should be simple enough, and the user in #1138 is using 1.28.2 and cannot upgrade due to this bug.
> BUG: Add missing deprecated EncodedStreamObject functions

- PyPDF2/generic.py
- tests/test_merger.py
iaw pdf spec, page 583
See #1145
> ROB : Cope with null params for FitH /FitV destination

- PyPDF2/generic.py
See #332
Co-authored-by: speedplane <mes65@cornell.edu>
> MAINT: Add diagnostic output to exception in read_from_stream

- PyPDF2/_encryption.py
It seems to be save to ignore the /Perms entry:
Qpdf ignores it:
https://github.com/qpdf/qpdf/blob/main/libqpdf/QPDF_encryption.cc#L1064
pdfbox ignores it:
https://github.com/apache/pdfbox/blob/dc1a75027d5bebf95a3330f6298a533e78e0b99e/pdfbox/src/main/java/org/apache/pdfbox/pdmodel/encryption/StandardSecurityHandler.java#L311
Closes #378
> BUG: Ignore if '/Perms' verify failed

- PyPDF2/_cmap.py
- tests/test_workflows.py
> ROB: Cope with utf16 character for space calculation

- PyPDF2/_writer.py
Closes #434
Co-authored-by: liuzhuoling <liuzhuoling@mycapital.net>
> BUG: Set /AS for /Btn form fields in writer

- PyPDF2/_merger.py
> BUG: Typo in warning message

- PyPDF2/filters.py
- tests/test_workflows.py
See https://github.com/py-pdf/PyPDF2/issues/1143#issuecomment-1193329917 , 2nd part
> ROB: Cope with empty DecodeParams

- PyPDF2/_cmap.py
- PyPDF2/_reader.py
- tests/test_reader.py
a) cmap : strip lines when processing cmap from fonts
b) look for %EOF up to beginning of file
test file in #134
> ROB : fix loading of file from #134

- PyPDF2/_encryption.py
- tests/test_page.py
> BUG: u_hash in AlgV4.compute_key

- PyPDF2/_page.py
- tests/test_page.py
Graphic state shall store also the font, font size,....
#1142
> BUG : incomplete Graphic State save/restore(#1142)

- PyPDF2/_reader.py
- tests/test_reader.py
Named dest are stored in a dictionnary in PDF 1.1
TODO : a test for named destination stored in name tree should be added to improve coverage
[#1173)
> BUG : Named Dest in PDF1.1(#1173)

- setup.cfg
Changelog file was updated from `CHANGELOG` to `CHANGELOG.md` in https://github.com/py-pdf/PyPDF2/pull/1023, but the link in package metadata has not been not updated.
> Fix changelog link in package metadata

- PyPDF2/_page.py
- tests/test_workflows.py
add new capability to filter text extraction on orientation
Deprecations: PageObject.extract_text no longer uses the `Tj_sep` and `TJ_sep` parameters.
cf #1071
> ENH: Add orientation param for text_extraction (# 1071)

- PyPDF2/_reader.py
- PyPDF2/errors.py
- tests/test_reader.py
closes https://github.com/py-pdf/PyPDF2/issues/1200
- Would be good to have clearer distinction of some well defined errors (that we want to detect) from the generic `PdfReadError`:
- WrongPasswordError
- FileNotDecryptedError
- EmptyFileError
- This makes it cleaner for error catching and handling (instead of inspecting the args within the error message)
> MAINT: Introduce WrongPasswordError / FileNotDecryptedError / EmptyFileError

- PyPDF2/filters.py
- tests/test_filters.py
According to 'TABLE 3.4 Entries common to all stream dictionaries', no IndirectObject is expected there.
But also:
> Any object in a PDF file may be labeled as an indirect object.
Closes #399
> BUG: Allow IndirectObjects as stream filters

- PyPDF2/generic.py
- tests/test_generic.py
> BUG : fix stream truncated prematurly

- .github/workflows/github-ci.yaml
- setup.cfg
PR modifies the package CI job in two ways:
1. Pass `package` to `check-wheel-contents` (see [action failure example](https://github.com/MasterOdin/PyPDF2/runs/7841851535?check_suite_focus=true)). This makes it so that `check-wheel-contents` verifies that each file in the package are actually in the wheel following their directory structure.
2. Have CI steps that verify we can install the package, and that we can run a minimal example with it (see [action failure example](https://github.com/MasterOdin/PyPDF2/runs/7841756654?check_suite_focus=true))
Either of these steps would have been sufficient to have caught #1242 per the example runs above.
> Modify CI to better verify built package contents

- PyPDF2/_utils.py
I think that part is dead code, because it's prevented by `stream.tell() < to_read`
> MAINT: Remove unreachable code in read_block_backwards

- PyPDF2/_encryption.py
> ROB : fix decryt returning empty bytestring

- setup.cfg
I stumbled upon this while having an older typing_extensions version
installed. According to my investigation TypeAlias was introduced with
typing_extensions 3.10.0 which makes sense since it is a Python 3.10
feature.
> Add min version for typing_extensions requirement

- PyPDF2/generic/_data_structures.py
- tests/test_page.py
> ROB: Add required line separators in ContentStream ArrayObjects

- PyPDF2/generic/_base.py
- tests/test_generic.py
Since Python 2.2 (PEP 237), integers cannot throw overflow exceptions.
> MAINT: Remove catching OverflowException

- PyPDF2/_page.py
- PyPDF2/_reader.py
- PyPDF2/_writer.py
- PyPDF2/types.py
PyPDF2 has some dependencies that make proper typing hard:
* PdfReader has the `pages` property which returns a `List[PageObject]`
* PageObject has the `pdf` property which returns the `PdfReader` it belongs to
The simplest solution would be to put both classes in the same file. I don't want that as it makes PRs hard to read. Additionally, bigger files mean merge conflicts happen more often.
The other way is to just not use type annotations for one of the objects.
The solution I want to go with is to define a "Protocol" ([PEP 544](https://peps.python.org/pep-0544/)). A protocol just states which methods a class is expected to have (with their function signature). It's duck typing:
> If it walks like a duck and it quacks like a duck, then it must be a duck
So we define the expected …
> MAINT: PdfReaderProtocol

- docs/user/cropping-and-transforming.md
`scale` accepts two params - `sx` and `sy`, `scale_by` - one `factor`.
> DOCS: Replace `scale` with `scale_by`

- PyPDF2/_page.py
When pdf has no crobox, artbox, etc, they are fallback to mediabox. As they are lazy, `self.cropbox` returns the `mediabox` copy which already was scaled.
> BUG: Avoid scaling cropbox twice

- docs/user/adding-pdf-annotations.md
Modify sample code for annotation builder to use background_color property instead of bg_color
> DOC: Fix AnnotationBuilder.free_text example

- PyPDF2/_cmap.py
- tests/test_cmap.py
> MultiLine bfrange in cmap

- PyPDF2/_encryption.py
fix #1288 
the specification says:
> To understand the algorithm below, it is necessary to treat the O and U strings in the Encrypt dictionary
> as made up of three sections. The first 32 bytes are a hash value (explained below). The next 8 bytes are
> called the Validation Salt. The final 8 bytes are called the Key Salt.
so `/U` and `/O` should be 48-bytes data.
but for the pdf which causes #1288 , `/O` 's length is 127-bytes, the redundant data are zeros.
> fix if u_value contains redundant data

- PyPDF2/_reader.py
- tests/test_reader.py
fixes #328
problem is observed in pdfs where the xref table in previous versions are not starting at 0 where _zero_xref was changing index which should not
> ROB : fix offset correction in revised PDF

- PyPDF2/generic/_data_structures.py
- tests/test_workflows.py
fix some images reading when some operations are inserted between EI and Q
end of image is now considered with [whitespace]EI[whitespace] (4 characters should be sufficient)
fixes #1090
> ROB : fix image extraction

- PyPDF2/_reader.py
- PyPDF2/_utils.py
- PyPDF2/_writer.py
- PyPDF2/merger.py
In python 2 it is still necessary to pass the class and object of the super function. 
This is missing in a few places.
The error looks like this:
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "<stdin>", line 3, in __init__
TypeError: super() takes at least 1 argument (0 given)
```
Our customers still use python 2 so we need Pypdf2 in a python 2 compatible version. 
Unfortunatly, it is not possible to migrate to python 3 soon, thus it would be very to fix this. Thanks!
> BUG: Adjust 'super' calls for Python 2

- PyPDF2/_cmap.py
- PyPDF2/_reader.py
- PyPDF2/generic/_base.py
- PyPDF2/generic/_data_structures.py
- tests/test_generic.py
fixes #1329
*prevent loop within dictionnaries where objects not respecting standard *fix cmap warnings due to "numbered" characters ( #2d instead of -) *apply unnumbering to nameobject
*add _get_indirect_object for debug/dev purpose
*add some missing seeks (no issue reported yet)
> ROB : fix infinite loop due to Invalid object

- tests/test_utils.py
- tests/test_workflows.py
Replace the warning-as-exception checks with use of `pytest.warns()`
that is more semantically correct and works correctly when the tests
are run without -Werror (e.g. because -Werror tends to cause test suites
to crash on irrelevant deprecation warnings from other components).
While at it, replace the homegrown exception checks in test_orientations
with `pytest.raises()`.
> TST: Use pytest.warns() for warnings, and .raises() for exceptions

- PyPDF2/_page.py
- tests/test_page.py
Error detected during analysis of #1280
> FIX : Fix Error in transformations

- PyPDF2/_cmap.py
- PyPDF2/_page.py
- PyPDF2/generic/_base.py
- tests/test_generic.py
- tests/test_merger.py
> ROB : improve nameobject reading/writing

- PyPDF2/generic/_utils.py
Certain PDF libraries do embed images as base64 strings. This causes performance issues in `read_string_from_stream` due to incremental string concatenation, byte by byte.
PDF Lib in our case is
```
<xmp:CreatorTool>Canon iR-ADV C256  PDF</xmp:CreatorTool>
<pdf:Producer>PDF Annotator 8.0.0.826 [Adobe PSL 1.3e for Canon</pdf:Producer>
```
> PI: Avoid string concatenation with large embedded base64-encoded images

- PyPDF2/_page.py
- PyPDF2/generic/_rectangle.py
- tests/test_generic.py
- tests/test_page.py
> ENH: Add rotation property and transfer_rotate_to_content

- PyPDF2/_writer.py
- tests/test_writer.py
> ROB : update_page_form_field_values not failing if no fields

- PyPDF2/_page.py
https://github.com/py-pdf/PyPDF2/issues/1280#issuecomment-1251018614
> BUG: Errors in transfer_rotation_to_content()

- tests/test_generic.py
There is a saftey margin of a factor of 10 in both directions, so the test should be fairly stable. Tests #1350.
> TST: read_string_from_stream performance

- PyPDF2/_utils.py
- PyPDF2/filters.py
- tests/test_utils.py
- tests/test_workflows.py
DEV: Adjusted File classes __str__ and __repr__ to easy debugging
> BUG: Lookup index in _xobj_to_image can be ByteStringObject

- PyPDF2/_cmap.py
fixes #1370 
cope with cmap where the range contains first and last   code are on variable length.
Also fix cases where the code is on 3 characters only (not standard)
no test data available
> ROB: Cope with cmap from #1322

- PyPDF2/_cmap.py
- tests/test_cmap.py
fixes #1379
have not been able to identify why str is returned instead of bytes as usual prefer to convert locally
> ROB: Cope with str returned from get_data in cmap

- docs/user/add-watermark.md
`reader_stamp = PdfReader(stamp_pdf)`
`image_page = reader_stamp.pages[0]`
PageObject of the watermark is declared inside the for loop. It is not needed outside the for-loop.
> Remove watermark PageObject declaration as it is already present inside for-loop

- PyPDF2/_page.py
- resources/Sample_Td-matrix.pdf
- tests/test_page.py
This PR contains a bugfix which introduces a matrix multiplication [1 0 0 1 tx ty] * tm_matrix when processing operator Td (see 5.3.1 Text-Positioning Operators, p. 406). This is important in cases where the text matrix is not like [1 0 0 1 e f].
I added an ASCII-sample pdf file which contains such a text matrix:
```
10 0 0 7 0 0 Tm
41 30 Td
(Hello PDF 10 7!) Tj
```
The test file ST.2019.pdf of #1142 contains such text matrices:
```
9 -0 0 9 264.36 796.92 Tm
(201)Tj
(9)Tj
/C2_0 1 Tf
2.28 0 Td
<14A414A414D618D50A7A>Tj
```
Therefore I adjusted test iss_1142.
After generating a svg export of Sample_Td-matrix.pdf I found a problem at the visitor-calls of #1252: One may get the wrong text matrix when an operator like Tm is executed together with not yet written text-output. I didn't want to …
> BUG: td matrix

- PyPDF2/_page.py
- PyPDF2/filters.py
- docs/user/encryption-decryption.md
- docs/user/extract-images.md
- docs/user/installation.md
- setup.cfg
- tests/test_filters.py
- tests/test_reader.py
> PKG: Declare Pillow as optional dependency

- tests/bench.py
- tests/test_generic.py
The test before was to brittle. We need to keep an open eye to the benchmarks in future, but also be careful with interpreting the numbers.
Credits to mergezalot in PR #1413
> DEV: Modify read_string_from_stream to a benchmark

- PyPDF2/_cmap.py
- tests/test_workflows.py
> FIX : ToUnicode stores /Identity-H instead of stream

- PyPDF2/generic/_data_structures.py
- tests/test_generic.py
fixes #1427
add a new function to easily remove an outline
> ENH : add a easy function to remove an outline

- docs/dev/pdf-format.md
fixed a couple of typos and added a placeholder mini explanation for `42`(might need something better context wise but I don't feeling comfortable expanding on the page too much for now).
> DOC: Typos in PDF format documentation

- PyPDF2/_writer.py
- tests/test_javascript.py
fixes #1425, #1420 and #482
(extracted from #1431)
> FIX : JS executed twice

- .github/workflows/github-ci.yaml
Closes #1451 
This sets the test suite to use `ubuntu-20.04` as opposed to `ubuntu-latest` as the latter switched over in the last day or so to using `ubuntu-22.04` and that broke testing Python 3.6. Ubuntu 20.04 has maintenance fixes for another ~2.5 years, and is supported critically for another 5 years after that, so the OS itself should be fine until we drop support for Python 3.6, and could then switch to `ubuntu-22.04`. It's also possible that the latter image will become compatible with Python 3.6 as well, but who knows.
> TST: Use Ubuntu 20.04 for running CI test suite

- docs/conf.py
- docs/index.rst
- docs/modules/PaperSize.rst
edited the index.rst file in the doc folder and created the PaperSize.rst file in the module folder. 
Tested it with sphinx to see results. (Worked)
> Created Documentation for the PaperSize class

- PyPDF2/_reader.py
- tests/test_reader.py
- tests/test_writer.py
main change : get_object(int) now available
> ENH: Make PdfReader.get_object accept integer arguments

- PyPDF2/_merger.py
- PyPDF2/pagerange.py
- tests/test_merger.py
> MAINT: Add List of pages to PageRangeSpec

- PyPDF2/_reader.py
- PyPDF2/_writer.py
- PyPDF2/constants.py
- tests/test_reader.py
- tests/test_writer.py
NOTE!!!!
this currently returns only an empty list . Peding to  PR#1371
> ENH: Add 'threads' property to PdfWriter

- PyPDF2/_encryption.py
Fixes #1221
Credit goes to Alper ahmetoglu for the fix
Co-authored-by: Alper Ahmetoglu <ahmetoglu.alper@gmail.com>
> ROB: Padding issue with AES encryption

- PyPDF2/_page.py
- PyPDF2/_reader.py
- PyPDF2/_writer.py
- pyproject.toml
- tests/__init__.py
- tests/test_generic.py
- tests/test_reader.py
- tests/test_writer.py
Small cleanup after #1467
See #1187
> MAINT: indirect_ref ➔ indirect_reference

- README.md
(given master branch is further ahead than stable package)
> DOC: Changed 'latest' for 'stable'

- docs/conf.py
Added `myst_all_links_external = True` to conf.py's global configuration as described [here](https://myst-parser.readthedocs.io/en/latest/configuration.html)
Closes #1492
> MAINT: Changed conf.py to make myst parse all links as simple hyperlinks

- README.md
The link to migration guide in README points to diff instead of the actual guide.
> DOC: fix migration guide link

- pypdf/_page_labels.py
- pypdf/_protocols.py
- pypdf/_reader.py
- tests/test_page_labels.py
- tests/test_reader.py
Introduce a new PdfReader property `page_labels` that returns a list of strings.
In most cases, the list will just be
```
['1', '2', '3', '4', '5']
```
or similar, but sometimes it will be:
```
['i', 'ii', 'iii', 'iv', '1', '2', '3', '4', '5']
```
* Stackoverflow: [Retrieve Custom page labels from document with pyPDF](https://stackoverflow.com/questions/12360999/retrieve-custom-page-labels-from-document-with-pypdf)
> ENH: Add support for page labels

- pypdf/_cmap.py
- pypdf/_codecs/__init__.py
- pypdf/_reader.py
- pypdf/_writer.py
- pypdf/generic/_annotations.py
- pypdf/generic/_utils.py
- pypdf/xmp.py
- tests/test_generic.py
This PR aims at making minor changes that do not influence readability in a negative way and help (a tiny bit) to make pypdf faster.
https://pypi.org/project/specialist/ was used.
You can see the specialized instructions with the `dis` module:
```python
python            
Python 3.11.0 (main, Oct 29 2022, 16:38:13) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dis
>>> your_function = lambda n: n * 1.5
>>> dis.dis(your_function, adaptive=True)
1           0 RESUME                   0
2 LOAD_FAST                0 (n)
4 LOAD_CONST               1 (1.5)
6 BINARY_OP                5 (*)
10 RETURN_VALUE
>>> your_function(1.5)
2.25
>>> your_function(2.5)
3.75
>>> your_function(3.5)
5.25
>>> your_function(4.5)
6.75
>>> your_function(5.5) …
```
> PERF: Help the specializing adpative interpreter

- CONTRIBUTORS.md
- requirements/docs.in
- requirements/docs.txt
Internal markdown links in docs did not work due to a bug in myst-parser. We can use an older version of myst-parser until the bug is fixed.
Example: On page: https://pypdf.readthedocs.io/en/stable/dev/intro.html, link to "See testing pypdf with pytest"
Related issue: https://github.com/executablebooks/MyST-Parser/issues/658
> DOC: Fix linked markdown documents

- docs/conf.py
- docs/dev/documentation.md
- docs/index.rst
- make_changelog.py
- mutmut_config.py
- pypdf/_encryption.py
- pypdf/_merger.py
- pypdf/_page.py
- pypdf/_page_labels.py
- pypdf/_protocols.py
- pypdf/_reader.py
- pypdf/_security.py
- pypdf/_utils.py
- pypdf/_writer.py
- pypdf/constants.py
- pypdf/filters.py
- pypdf/generic/__init__.py
- pypdf/generic/_annotations.py
- pypdf/generic/_base.py
- pypdf/generic/_data_structures.py
- pypdf/generic/_fit.py
- pypdf/generic/_outline.py
- pypdf/generic/_rectangle.py
- pypdf/generic/_utils.py
- pypdf/pagerange.py
- pypdf/xmp.py
- tests/__init__.py
The Google Docstring style is way more readable than ReST style docstrings.
Additionally, replace most instances of 'pragma: no-cover' by 'deprecated'
Tools used:
- pyment
- pydocstyle
> DOC: Use google style docstrings

- pypdf/_reader.py
- pypdf/generic/_data_structures.py
- tests/test_reader.py
fixes #1468
Add an optional parameter to `get_form_text_fields`
TBC : behavior with multiple fields with same name create sequence _2, _3, ... does not seem to be applied
Pending : Test to be added
> ENH: Accept hierarchical fields

- tests/test_reader.py
- tests/test_writer.py
By annotating these tests, we can use pytest markers to skip external tests and tests that depend on sample-files.
> Annotate tests appropriately

- pypdf/generic/_data_structures.py
- tests/test_workflows.py
> ENH: Accept inline images with space before EI

- pypdf/_utils.py
- pypdf/generic/_base.py
- pypdf/generic/_data_structures.py
- tests/test_utils.py
This was initially motivated by `NumberObject.read_from_stream`, which was calling `read_until_regex` with the default value of `ignore_eof=False` and thus raising exceptions like:
```
PyPDF2.errors.PdfStreamError: Stream has ended unexpectedly
```
https://github.com/py-pdf/PyPDF2/commit/431ba7092037af7d1c296f8f280aca167859ce61 demonstrates a similar fix for `NameObject.read_from_stream`.
From discussion in https://github.com/py-pdf/pypdf/pull/1505, it was realized that the change to `NumberObject.read_from_stream` had now made ALL callers of `read_until_regex` pass `ignore_eof=True`. It's cleaner to remove the parameter entirely and change the default behaviour.
> ROB: ignore_eof everywhere for read_until_regex

- docs/user/forms.md
The following code example does not use the fields variable. It is defined but not used.
> DOC: Removed the redundant `fields` variable

- tests/test_merger.py
Avoid having two tests write to the same filename "stream.pdf".
When a writing test has completed and actually written a file, unlink the destination file, so that it does not litter the filesystem after the test.
> TST: Unlink test output once successfully written

- pypdf/_encryption.py
- pypdf/_merger.py
- pypdf/_page.py
- pypdf/_reader.py
- pypdf/_security.py
- pypdf/_utils.py
- pypdf/_writer.py
- pypdf/generic/_annotations.py
- pypdf/generic/_data_structures.py
- pypdf/generic/_fit.py
- pypdf/generic/_utils.py
- pypdf/pagerange.py
- setup.cfg
Found a couple of issues with darglint: https://pypi.org/project/darglint/
However, there are many false-positives:
1. Properties: I don't want `Returns` for any property
2. Deprecations: Deprecated arguments should not be documented; the docstrings of deprecated code should not be changed.
> STY: Docstring formatting of darglint

- .pre-commit-config.yaml
- docs/conf.py
- docs/user/adding-pdf-annotations.md
- pypdf/_encryption.py
- pypdf/_merger.py
- pypdf/_page.py
- pypdf/_page_labels.py
- pypdf/_reader.py
- pypdf/_security.py
- pypdf/_utils.py
- pypdf/_writer.py
- pypdf/constants.py
- pypdf/filters.py
- pypdf/generic/_base.py
- pypdf/generic/_data_structures.py
- pypdf/generic/_fit.py
- pypdf/generic/_rectangle.py
- pypdf/generic/_utils.py
- pypdf/pagerange.py
- pypdf/xmp.py
- pyproject.toml
- tests/bench.py
- tests/test_filters.py
- tests/test_generic.py
- tests/test_page.py
- tests/test_reader.py
- tests/test_workflows.py
- tests/test_writer.py
See https://pypi.org/project/docformatter/
I tried pre-commit, but docformatter collides with black for docstrings of functions that contain a function:
```
-   repo: https://github.com/PyCQA/docformatter
rev: v1.6.0.rc1
hooks:
-   id: docformatter
name: Check docstring formatting
args: [--in-place, --wrap-summaries=0, --wrap-descriptions=0, --pre-summary-newline]
```
> STY: Apply docformatter

- docs/user/extract-text.md
`s/shortcomming/shortcoming/` - https://www.merriam-webster.com/dictionary/shortcoming
I also added / removed some spacing around headers so that there's a unified one space before and after all headers on the page.
> DOC: fix typo on extract text page

- pypdf/_writer.py
- tests/test_writer.py
This PR is a preparation to completely get rid of decimal at some point. For now, I don't want to break peoples CI.
> MAINT: Remove decimal

- pypdf/_page.py
- tests/test_page.py
> BUG : Text extraction not working with one glyph to char sequence

- docs/user/cropping-and-transforming.md
- pypdf/_page.py
@pubpub-zz Continuing our discussion from https://github.com/py-pdf/pypdf/pull/879 and #1426 :-)
I'm not sure if exposing this that prominently is a good idea or if we should simply change it... but allowing people to easily switch back would potentially enable people to still get the old behavior if they need to
I also don't know if `MERGE_CROP_BOX` is a good name for this attribute.
> BUG: Switch from trimbox to cropbox when merging pages

- pypdf/_writer.py
- tests/test_writer.py
> ROB: Fix 2 cases of "object has no attribute 'indirect_reference'"

- tests/__init__.py
to reduce fail case due to network issue during committing
> TST : Add multiple retry on get_url

- tests/test_page.py
- tests/test_workflows.py
- tests/test_writer.py
It would be great if future tests could be marked appropriately, as they break the debian build daemons and CI, neither of which have direct access to the Internet.
> TST: Mark new external tests appropriately

- pypdf/_encryption.py
Fix bug "Incorrect IV length (it must be 16 bytes long) " due to len(data) == 0 on some encrypted PDF files.
> BUG: Allow decryption with empty password for AlgV5

- docs/index.rst
- docs/user/extract-attachments.md
- pypdf/_reader.py
- tests/test_writer.py
Add `PdfReader.attachments -> Dict[attachment_name, LazyLoader]` as a public interface.
`LazyLoader.read()` returns a list of bytes.
The heavy-lifting was done by @pubpub-zz  in #1611
> ENH: Add reader.attachments public interface

- pyproject.toml
- tests/test_cmap.py
- tests/test_filters.py
- tests/test_generic.py
- tests/test_merger.py
- tests/test_page.py
- tests/test_page_labels.py
- tests/test_pagerange.py
- tests/test_reader.py
- tests/test_utils.py
- tests/test_workflows.py
- tests/test_writer.py
- tests/test_xmp.py
* Use parenthesis for pytest markers: `@pytest.mark.slow` ->  `@pytest.mark.slow()`
* Make `pytest.raises` blocks smaller
* Make assert statements smaller
* Use [pytest.fail](https://docs.pytest.org/en/7.1.x/reference/reference.html#pytest-fail) instead of `assert False`
> STY: Ruff rules

- docs/user/extract-text.md
- pypdf/_page.py
visitor_operand_before, visitor_operand_after are called on `(operator, operands, cm_matrix, tm_matrix)` in _page.py. However, the documentation said the first argument is 'operand.'
> DOC: Fix misusage of the word 'operand' in documentation.

- pypdf/_writer.py
PdfWriter.set_need_appearances_writer() (whether called directly or indirectly by PdfWriter.update_page_form_field_values()) fails to create the /Root/AcroForm object correctly when it doesn't already exist in the PdfWriter object.
See my comment [here](https://github.com/py-pdf/pypdf/issues/355#issuecomment-1433319593) for more details.
Fixes #355
> BUG: Write /Root/AcroForm in set_need_appearances_writer

- pypdf/_writer.py
Without this, the logging module logs another error: TypeError: not all arguments converted during string formatting
> BUG: Pass logging parameters correctly in set_need_appearances_writer

- pypdf/_reader.py
- tests/test_reader.py
> ROB: Allow more whitespace within linearized file

- pypdf/_page.py
- tests/test_generic.py
- tests/test_page.py
- tests/test_workflows.py
- tests/test_writer.py
fixes  #1654
ContentStream must be stored as individual objects
> BUG : compress_content_stream not readable in acrobat

- pypdf/_cmap.py
- tests/test_cmap.py
> ROB: Widths def in cmap calls indirectObject

- pypdf/_writer.py
- tests/test_writer.py
extend append/Merge to pass PageObject list to ease some processing
> ENH: Extend PdfWriter.append() to pageObjects

- pypdf/_reader.py
- tests/test_reader.py
accepts destination stored in "/D" of a dictionaryObject in accordance with §2 page 584
fixes #1710
> ROB: Accept DictionaryObject in /D of NamedDestination

- pypdf/_utils.py
- pypdf/generic/_data_structures.py
- tests/test_generic.py
the field /Length is normally required, but acrobat reader and other reader are tolerant
the mod in _utils.py is fixing a bug detected with the updated test
closes #1715
> ROB: Tolerate streams without length field

- pypdf/_writer.py
- pypdf/generic/_data_structures.py
- tests/conftest.py
- tests/test_generic.py
- tests/test_merger.py
- tests/test_page.py
- tests/test_reader.py
- tests/test_workflows.py
- tests/test_writer.py
On the positive side:
+ Tests become easier to read
+ Files cleanup cannot be forgotten
+ Tests can be copy-pasted into the docs
Neutral:
o If the test run fails, you can see where the file was written
and it's not directly deleted
Negative:
- If the run does not fail (loudly) but you want to inspect the generated PDF, you have to 'assert False' or similar. That is harder to figure out than commenting out a Path.unlink() line
> TST: Use fixtures to create files in temporary folders

- pypdf/_writer.py
- tests/test_writer.py
> BUG: 'DictionaryObject' object has no attribute 'indirect_reference'

- pypdf/filters.py
- tests/conftest.py
- tests/test_generic.py
> ROB: Handle params NullObject in decode_stream_data

- docs/index.rst
- docs/meta/scope-of-pypdf.md
We get several requests that are out of scope:
* https://github.com/py-pdf/pypdf/issues/1731
* https://github.com/py-pdf/pypdf/issues/1696
* https://github.com/py-pdf/pypdf/issues/1588
* https://github.com/py-pdf/pypdf/issues/1457
This document should help to guide users if/why their request is out of scope. When we see an out-of-scope request we can point to this doucment.
> DOC: Project scope

- docs/user/encryption-decryption.md
- pypdf/_writer.py
- tests/test_encryption.py
- tests/test_workflows.py
- tests/test_writer.py
> SEC: Warn about PDF encryption security

- pypdf/_reader.py
- tests/test_reader.py
fixes #1758
This is an alternative which also reports when "opening" the file a damaged header
Change to the check of footer (log in case of not strict) should be better for linearization
also pdf_header should report the actual header for better understanding
> ROB: Capture UnicodeDecodeError at PdfReader.pdf_header

- pypdf/_protocols.py
- pypdf/generic/_base.py
- pypdf/generic/_data_structures.py
- tests/test_writer.py
fixes  #1767
the issue is due to object 589/0 : this object corresponds to 2 object the file trailer but also an XObject corresponding to the filled text ("test") because of that the object tries to be duplicated inducing the loop. This loop is not normal and I've fixed as a robustness improvement. If you run your code the text "test" will be missing as it is hidden by the trailer object.
> ROB: Prevent loop in Cloning

- pypdf/_writer.py
- tests/test_workflows.py
I'm uncertain if we want to re-generate this even if it's present when we encrypt the file.
pdfrw: Not at all
PyMuPDF:
* Parameter `"no_new_id"` in `Document.save`: Use it to suppress updating the second item of the document ``/ID`` which in PDF indicates that the original file has been updated. If the PDF has no ``/ID`` at all yet, then no new one will be created either.
* creation of PDF documents: they will now always carry a PDF identification (``/ID`` field) in the document trailer. See https://github.com/pymupdf/PyMuPDF/issues/691
> MAINT: Move generation of file identifiers to a method

- pypdf/_reader.py
- tests/test_reader.py
> ROB: Invalid startxref pointing 1 char before

- pypdf/_page.py
- tests/test_page.py
I am the maintainer of [PSUtils](https://github.com/rrthomas/psutils). I am adding PDF support, and rewriting the code in Python. pyPDF was a significant motivation for the choice of language, so thanks for that!
I need to express vertical and horizontal page flips, and the simplest way to achieve this seemed to be to add a general `transform` method to `Transformation` (I need all the different sorts of transformations to be applied repeatedly to the same page, so it's easier to change a `Transformation` than to make multiple copies of a page and transform that.) I have done this in the simplest way I could; it might be desired for the method to take a `CompressedTransformationMatrix` too.
If you agree to add an API something like this, I'll happily add some tests. (At the moment I just …
> ENH: Add transform method to Transformation

- pypdf/_cmap.py
- tests/test_cmap.py
fixes #1782
UCS2 are to be read as utf-16be
> ENH: Cope with UC2 fonts in text_extraction

- pypdf/_utils.py
- tests/test_utils.py
BUG: `deprecate_with_replacement` was potentially giving the wrong error message (version 3.0.0 instead of the actual version)
> TST: Deprecation warnings/errors

- pypdf/filters.py
- tests/test_filters.py
The PDF contained an image in PA mode:
* P: 8-bit pixels, mapped to any other mode using a color palette
* PA: P with alpha
See #1801
> BUG: Convert color space before saving

- docs/user/forms.md
Update docs to use append rather than add_page so that the PDF structure is copied. This ensures the form structure is kept which is necessary for some PDFs.
See #1790
Closes #1792
Closes #1804
> DOC: Use append instead of add_page

- pypdf/_encryption.py
- tests/test_encryption.py
This PR makes #1816 a bit smaller
Full credit goes to @exiledkingcc
> MAINT: Prepare for adding AES enryption support

- pypdf/_encryption.py
- tests/test_encryption.py
Pass it through to compute_U_value / compute_O_value
"R" is the encryption algorithm revision.
Also fix a bug I (Martin) just introduced in
compute_O_value by setting the token_bytes=4 and not 16.
All credit for refactoring goes to exiledkingcc
This PR makes #1816 smaller.
> MAINT: Add R parameter to generate_values

- pypdf/_cmap.py
- tests/test_cmap.py
a new encoding to be considered.
fixes #1809
> ENH: Extend cmap compatibilty to GBK_EUC_H/V

- pypdf/generic/_data_structures.py
- tests/test_generic.py
> BUG: Accept XYZ destination with zoom missing (default to zoom=0.0)

- docs/meta/comparisons.md
Added my take on the `pdfplumber` library compared to PyPDF.
> DOC: Add comparison with pdfplumber

- pypdf/_reader.py
- tests/test_page.py
Fixes https://github.com/py-pdf/pypdf/issues/500
these PDF are not compliant with Standard (Type is mandatory in page tree nodes however Acrobat Reader can open them
Robustness improved
criteria to consider it as a page  : /Kids missing
> ROB: Handle missing /Type entry in Page tree

- docs/user/file-size.md
Closes https://github.com/py-pdf/pypdf/issues/1786
Changing the viewboxes ("cropping") has no impact on file size
Removing complete pages only has an impact if the connected resources are also removed
> DOC: Expand file size explanations

- pypdf/generic/_data_structures.py
- requirements/ci-3.11.txt
- requirements/ci.in
- requirements/ci.txt
- tests/test_reader.py
> BUG: Prevent infinite loop when no character follows after a comment

- pypdf/generic/_utils.py
> Problem
Some pdfs contain Latin characters, and when trying to read them using pypdf, it throws the following exception.|
```Traceback (most recent call last):
text = page.extract_text()
File "/Users/.pyenv/versions/3.10.3/lib/python3.10/site-packages/pypdf/_page.py", line 1851, in extract_text
return self._extract_text(
File "/Users/.pyenv/versions/3.10.3/lib/python3.10/site-packages/pypdf/_page.py", line 1356, in _extract_text
content = ContentStream(content, pdf, "bytes")
File "/Users/.pyenv/versions/3.10.3/lib/python3.10/site-packages/pypdf/generic/_data_structures.py", line 877, in __init__
self.__parse_content_stream(stream_bytes)
File "/Users/.pyenv/versions/3.10.3/lib/python3.10/site-packages/pypdf/generic/_data_structures.py", line 943, in __parse_content_stream …
```
> BUG: Ignore UTF-8 decode errors

- make_changelog.py
With this PR, we can run the script multiple times and keep the same result.
> CI: Leave CHANGELOG if it's recent

- pypdf/_merger.py
- tests/test_encryption.py
- tests/test_generic.py
- tests/test_merger.py
- tests/test_workflows.py
- tests/test_writer.py
> DEP: Deprecate PdfMerger

- tox.ini
I found this was required to run the tests with tox in #1884.
> MAINT: Install pytest-socket in tox

- docs/user/metadata.md
This commit introduces significant enhancements to the existing code for adding metadata to a PDF file. The changes aim to improve the readability, completeness, and professionalism of the metadata properties. The following updates have been made:
- Added new metadata properties, including Title, Subject, Keywords, CreationDate, ModDate, Creator, and CustomField, providing more comprehensive information about the PDF document.
- Refactored the code to utilize the datetime module to obtain the current date and time in the desired format, ensuring accurate and standardized timestamping.
- Introduced an optional feature to include UTC time, enabling precise timestamping in different time zones if required.
- Preserved the ability to retain old metadata by including the metadata variable, …
> DOC: Add details how to write metadata

- pypdf/_utils.py
- pypdf/generic/_base.py
- pypdf/generic/_data_structures.py
- tests/test_utils.py
There are `int` and `long` in Python2, hex a `long` value will get a suffix 'L', which is no longer in Python3.
> MAINT: Clean residual Python2 code

- tests/test_reader.py
Test for https://github.com/py-pdf/pypdf/issues/1893
> TST: Add failing test for KeyError: '/Alternate'

- pypdf/filters.py
- tests/test_filters.py
- tests/test_reader.py
fixes #1893
applies the same solution as for original ICCbased
> BUG: Handle missing /Alternate in indexed/ICCbased colorspaces

- pypdf/_page.py
- pypdf/_writer.py
- tests/test_page.py
> BUG: File expansion when updating with Page Contents

- pypdf/_encryption.py
- pypdf/generic/_base.py
- tests/test_encryption.py
* `CryptFilter.encrypt_object` implemented
* `AlgV5.generate_values` now crops the user_password / owner_password to 127 bytes
* The `EncryptAlgorithm` Enum was added. It contains the parameter V (version), R (revision), and length
* `Encryption.encrypt_object` was added
* `Encryption.write_entry` was added
* The static method `Encryption.make` was added
This PR was only made to make it easier to merge the other changes / to avoid merge conflicts of other changes with #1816 . Full credit goes to exiledkingcc.
The PR is marked as "MAINT" as it doesn't add a new feature that an end-user could use.
> MAINT: Prepare for adding AES support via #1816

- pypdf/filters.py
- tests/test_filters.py
closes #1912
the issue is dealing with some images being encoded with 2 filters being cascaded
> BUG : cascaded filters in image objects

- pypdf/generic/_rectangle.py
The setters lower_left / lower_right / upper_left / upper_right are now consistent with the getters.
Closes #1842
> MAINT: Adjust type annotations in _rectangle.py

- pypdf/_reader.py
- tests/test_reader.py
> BUG: Add the TK.SIZE into the trailer

- docs/dev/testing.md
With just the dev requirements installed, pytest fails to run and exits with `pytest: error: unrecognized arguments: --disable-socket` due to `pytest-socket` and `pytest-timeout` not being in the dev requirements.
> DOC: Clarify which requirements file is needed to run the tests

- pypdf/_writer.py
- tests/test_writer.py
> BUG: Remove unused objects when cloning_from

- pypdf/_writer.py
- tests/test_writer.py
> Bug: add_named_destination() maintains named destination list sort order

- pypdf/_reader.py
I encountered this bug while playing around with the library. Seemed like a fairly straightforward fix, but if there are issues with doing this, let me know.
> BUG: PdfReader.get_fields() attempts to delete non-existing index "/Off"

- pypdf/_encryption.py
- pypdf/_writer.py
- tests/test_encryption.py
- tests/test_workflows.py
- tests/test_writer.py
* PdfWriter.encrypt: Add 'algorithm' parameter
* PdfWriter: Add _encryption property
* PdfWriter: Add _encrypt_entry property
This change was made in another PR to avoid merge conflicts / get it merged soon. Full credit for the work goes to exiledkingcc in #1816
> ENH: Add AES support for encrypting PDF files

- pypdf/_encryption.py
- pypdf/_writer.py
- pypdf/generic/_base.py
- pypdf/generic/_data_structures.py
- pypdf/generic/_outline.py
- pypdf/xmp.py
- tests/test_generic.py
> MAINT: Deprecate the encryption_key parameter of write_to_stream

- pypdf/_reader.py
- tests/test_reader.py
> BUG: Dates conversion not working with Z00'00'

- pypdf/filters.py
- tests/test_filters.py
closes #1895
CMYK image without decode requires reverting scale (cf p243,2§ last sentence in PDF 1.7 spec)
> BUG: Inverse color in CMYK images

- docs/user/add-watermark.md
- pypdf/_page.py
- tests/test_page.py
- tests/test_writer.py
add also over param in merge_page
closes #1951
closes #1953
> BUG: Prevent updating page contents after merging page (stamping/watermarking)

- pypdf/_writer.py
I have a PDF that when read in non-strict mode, yields a "/AcroFrom" = None. This gates the block to ensure the block is skipped. Without it, the clone() call a few lines down will error with 
```
AttributeError: 'NoneType' object has no attribute 'clone'
```
> BUG: Check for AcroForm and ensure it is not None

- .github/workflows/github-ci.yaml
- .github/workflows/release.yaml
This PR has two goals:
* Ensure that I, as a maintainer, do releases more consistently and with less effort.
* Enable other trusted members of the pypdf community and the py-pdf organization to make releases to PyPI. That should typically not be done, but is a last resort in case I become inactive.
What was done:
* A new repository secret `FLIT_PASSWORD` was created via PyPI. It is a PyPI token for pypdf.
* A Github Action `release.yaml` (this PR) was created.
To ensure that you can write Markdown-style git tags, you can do this:
```
git config --global core.commentChar ";" 
```
I used pdfly for that. Looks mostly fine. It especially published to PyPI.
See "TODO" for what is missing.
* Make the release have rendered Markdown. I think I struggle with the fact that the body is a multi-line …
> DEV: Automate the release process

- pypdf/filters.py
- tests/test_filters.py
> BUG: Process CMYK in deflate images

- pypdf/constants.py
- pypdf/filters.py
- tests/test_filters.py
> BUG: Decode Black only/CMYK deviceN images

- .github/workflows/github-ci.yaml
- .github/workflows/release.yaml
Closes #1971 
PR fixes that new GitHub releases were lacking a body, where this was due to the fact that we were not outputting `tag_body` to `$GITHUB_ENV` so that it wasn't available in follow-up steps. However, because the body is a multiline string, we've got to wrap it in special syntax to get it to work (see [docs](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-of-a-multiline-string) for example).
See https://github.com/py-pdf/pypdf/actions/runs/5601580443/jobs/10245662760?pr=1985 as an example test run that shows it working in a test workflow.
> DEV: Add body to created GitHub release

- pypdf/_reader.py
- pypdf/_utils.py
- tests/test_utils.py
ensure compatiblity with all optional date fields formats as specified in pdf  1.7 spec
closes #1996
closes #1972
> BUG: Cope with different ISO date length

- pypdf/_writer.py
- tests/test_writer.py
> BUG: Search /DA in hierarchy fields

- pypdf/filters.py
- tests/test_filters.py
> BUG: Process lookup decoded as TextStringObjects

- pyproject.toml
pypdf uses the `formats` option for `Image.open`, which is not available before Pillow 8.0.0.
Closes #2019.
> ENH: Add minimum Pillow version requirement (closes #2019)

- pypdf/filters.py
- tests/test_filters.py
> BUG: Handle single element ColorSpace list

- .github/workflows/github-ci.yaml
- pypdf/_crypt_providers/__init__.py
- pypdf/_crypt_providers/_base.py
- pypdf/_crypt_providers/_cryptography.py
- pypdf/_crypt_providers/_fallback.py
- pypdf/_crypt_providers/_pycryptodome.py
- pypdf/_encryption.py
- pyproject.toml
- tests/test_encryption.py
Use the [`cryptography` package](https://pypi.org/project/cryptography/) (maintained by the Python Cryptographic Authority, pyca) as a fallback if [PyCryptodome](https://pypi.org/project/pycryptodome/) (maintained by Legrandin / Helder Eijs) is not installed.
Closes #1998
> ENH: Use `cryptography` for encryption/decryption as a fallback for PyCryptodome

- pypdf/_page.py
- pypdf/_utils.py
- tests/test_workflows.py
> ENH: Accelerate image list keys generation

- pypdf/filters.py
- tests/test_filters.py
closes #2030
there is a TODO in pypdf/filters.py:L889 as currently pillow does not accept( cf CMYK palette in https://github.com/python-pillow/Pillow/issues/7309)
> BUG: Fix indexed/CMYK images

- pypdf/_cmap.py
- tests/test_cmap.py
- tests/test_encryption.py
/uniHHHH glyphs seems to be generated in laTeX but is ok for other characters 
addressed partially in  #2016
addressed partially in #2038
> ENH: Process /uniHHHH for text_extract

- docs/user/file-size.md
- pypdf/_page.py
- pypdf/filters.py
- pypdf/generic/_data_structures.py
Provide more options / details on how to reduce the file size with compression.
See #1910
```
File    File name
size    The suffix is the compression level
-------------------
5321132 GeoTopo.pdf
9959402 out-0.pdf
5976025 out-1.pdf
5914204 out-2.pdf
5885818 out-3.pdf
5816263 out-4.pdf
5762359 out-5.pdf
5738259 out-6.pdf
5731877 out-7.pdf
5726121 out-8.pdf
5725267 out-9.pdf
```
Level 1 gives a very good improvement, but already level 2 might not be worth the CPU cycles.
Interestingly, the original is smaller than the best compression :warning:
> ENH: Add `level` parameter to compress_content_streams

- docs/user/encryption-decryption.md
- pypdf/_crypt_providers/__init__.py
- pyproject.toml
- tests/test_encryption.py
use `PyCryptodome` as a fallback
> CHANGE: cryptography as primary dependency

- docs/index.rst
- docs/user/post-processing-in-text-extraction.md
- pypdf/_page.py
See https://pypdf--2052.org.readthedocs.build/en/2052/user/post-processing-in-text-extraction.html
Closes #2046
> DOC: Post-processing page

- docs/user/file-size.md
This fixes a simple typo overlooked in my review from https://github.com/py-pdf/pypdf/pull/2044#discussion_r1278860217
> DOC: fix typo in file size docs

- pypdf/filters.py
- tests/test_filters.py
> BUG: JPX image without ColorSpace 

- pypdf/annotations/_markup_annotations.py
The object was not updating itself, but a temporary variable in it
Closes #2058
> BUG: Fix AnnotationBuilder.link

- tests/test_utils.py
The repository `https://github.com/timedegree/playground_files` no longer exists and thus the PDF is also gone.
> MAINT: Remove broken test

- tests/test_filters.py
- tests/test_images.py
A function `image_similarity` was introduced which quantifies visual similarities of two images via Mean Squared Error (MSE). This way we can compare the extracted images with what we expect.
We cannot make a byte-wise comparison as updates to PIL can change the representation.
The new function helps us to ensure that updates to the pypdf code don't break image extraction.
> TST: Compare extracted images against ground truth

- pypdf/filters.py
this commit makes `tests/test_page.py::test_image_new_property` cost from 8.98s to 5.69s on my machine, about x1.5 faster.
> PI: optimize _decode_png_prediction

- pypdf/_writer.py
- tests/test_writer.py
> BUG: append() fails when articles do not have /T

- pypdf/_reader.py
- tests/test_reader.py
> ROB: Cope with xref not followed by separator

- pypdf/_page.py
- tests/test_images.py
- tests/test_page.py
> BUG: prevent stall when accessing image in corrupted pdf

- pypdf/_reader.py
- tests/test_reader.py
> SEC: Avoid endless recursion of reading damaged PDF file

- pypdf/errors.py
It’s an exception raised by PyPdfError, I don’t see a reason to treat it
specially.
> MAINT: Make ParseError inherit from PyPdfError

- pyproject.toml
Trying to run the tests after `pip install -e '.[dev]'` results in:
ERROR tests/test_reader.py - pytest.PytestUnknownMarkWarning: Unknown pytest.mark.timeout - is this a typo?  You can register custom marks to avoid this
> DEV: Add pytest-timeout to the dev dependencies in pyproject.toml

- .pre-commit-config.yaml
- docs/user/encryption-decryption.md
- pypdf/_page.py
- pypdf/filters.py
- pypdf/generic/_base.py
- pypdf/generic/_data_structures.py
- pypdf/pagerange.py
- pypdf/papersizes.py
- pyproject.toml
- requirements/ci-3.11.txt
- tests/test_generic.py
- tests/test_reader.py
- tests/test_text_extraction.py
If the property does nothing else than wrapping an attribute, we can use the attribute directly. Once we need the property, we can re-introduce it.
While on it, pre-commit was also updated + the ruff version in CI.
Taken from https://github.com/py-pdf/pypdf/pull/2086
> MAINT: Remove unnecessary property + mypy fixes

- pypdf/_reader.py
- pypdf/_writer.py
- pypdf/filters.py
- pypdf/generic/_base.py
- pypdf/generic/_data_structures.py
Related to https://github.com/py-pdf/pypdf/pull/2099
> MAINT: ContentType._data setter uses only bytes

- pypdf/_page.py
> PI: Re-use content stream

- docs/user/add-watermark.md
This fixes some typos inside the watermarking docs and refers to `PageObject.transfer_rotation_to_content` which is currently hidden away in the API docs, but recommended before merging.
> DOC: Improve watermark docs

- .pre-commit-config.yaml
- pypdf/_text_extraction/__init__.py
- pypdf/generic/_utils.py
- pyproject.toml
- tests/test_filters.py
If we set upper limits then if someone wants to contribute more complex code then they need to justify in their pull request why they _need_ messier code than is already in the codebase.
```toml
[tool.ruff.mccabe]
max-complexity = 54  # Recommended: 10
[tool.ruff.pylint]
allow-magic-value-types = ["bytes", "float", "int", "str"]
max-args = 12  # Recommended: 5
max-branches = 36  # Recommended: 12
max-returns = 11  # Recommended: 6
max-statements = 176  # Recommended: 50
```
> DEV: Add upper limits for complexity

- .github/workflows/github-ci.yaml
Use the current version of Python 3.12 whether it is a pre-release or a production release as discussed at: https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#allow-pre-releases
This should run tests on [Python 3.12 rc1](https://www.python.org/download/pre-releases/) instead of hard coding __beta 4__.
> DEV: setup-python for Python 3.12 allow-prerelease: true in Github Actions

- pypdf/_encryption.py
- pypdf/_reader.py
- pypdf/filters.py
- pypdf/generic/_data_structures.py
- tests/test_page.py
This was introduced when I removed seemingly unnecessary calls to b_, a helper function that converts Union[bytes, str] to bytes.
Root-cause: Too little test coverage + wrong type annotations
Caused-by: 30331227ec3ef087f15f4c3828e2b6d95aa4ce0f
Closes #2111
> BUG: TypeError: can't concat str to bytes

- .github/ISSUE_TEMPLATE/bug-report.md
- pypdf/__init__.py
- pypdf/_crypt_providers/__init__.py
- pypdf/_crypt_providers/_cryptography.py
- pypdf/_crypt_providers/_fallback.py
- pypdf/_crypt_providers/_pycryptodome.py
We often need a couple of package versions to investigate issues. This command gives us a one-liner to get that data.
See #2107
> DEV: Add easy way to see all relevant versions

- pyproject.toml
This relaxes the version of `typing_extensions` required by PyPDF as proposed in #1950.
Please note that this change is not reflected in CI due to the reasons outlined in https://github.com/py-pdf/pypdf/issues/1950#issuecomment-1627387294, but I have tested it locally and some time ago on my fork of the project.
Closes #1950.
> MAINT: Relax typing_extensions version

- .gitignore
- make_changelog.py
> DEV: Ensure the REL commit message is consistently created

- pypdf/_writer.py
- tests/test_writer.py
> BUG: remove_images not operating in sub level forms

- pypdf/generic/_data_structures.py
- tests/test_writer.py
closes  #140  - late exchanges in the theads:
https://github.com/py-pdf/pypdf/issues/140#issuecomment-1685380549
the PDF is damaged.The length is an indirectobject that can not be found returning None.
> ROB: Cope with damaged PDF

- .github/workflows/github-ci.yaml
This was originally added by stefan on #2130
This allows anyone to manually run the workflow on their fork if desired with any branch.
See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
> DEV: Add workflow_dispatch to CI

- .github/workflows/github-ci.yaml
- tests/__init__.py
- tests/test_writer.py
Ensure `enable_socket` tests are not failing due to PDF download time:
1. Use the name that is also used in `test_image_extraction` to avoid duplicate downloads
2. Ensure download time is not counted in CI
> DEV: Download PDFs before executing the tests to not run into timeouts

- .github/workflows/github-ci.yaml
- tests/test_writer.py
This adds a test for the correct rendering of watermarked files.
Closes #2112
> TST: Add test for correct rendering of watermarks

- pypdf/_writer.py
- tests/test_writer.py
> BUG: Cope with missing /I in articles

- pypdf/_reader.py
- pypdf/_writer.py
- pypdf/generic/__init__.py
- pypdf/generic/_viewerpref.py
- tests/test_writer.py
closes #2105
still doc and test to be fixed/added
> ENH: Ease access to ViewerPreferences

- pypdf/_cmap.py
- tests/test_cmap.py
> BUG: Accept tabs in cmaps

- pypdf/filters.py
- tests/test_filters.py
> BUG: Fix conversion from 1 to LA

- README.md
- docs/index.rst
Based on https://github.com/py-pdf/pypdf/discussions/2171, feels like pdfly has a bit of a discovery problem. Adding a link at the front of pypdf's docs should hopefully help there.
> DOC: Mention pdfly on frontpage of docs

- pypdf/generic/_data_structures.py
- tests/test_writer.py
> ROB: Accept XYZ with no arguments

- pypdf/generic/_base.py
- tests/test_writer.py
if a object contains a indirect_reference, which points to the object it self, cloning it will cause infinite recursion.
for example: a page contains a link to self.
this will fix #2102
> SEC: Infinite recursion caused by IndirectObject clone

- pypdf/_writer.py
- tests/test_writer.py
> BUG: Cope with extra space in DA preventing font extraction

- pypdf/_cmap.py
- tests/test_cmap.py
> BUG: catch the case where w[0] is an IndirectObject instead of an int

- pypdf/_codecs/adobe_glyphs.py
> STY:  clean-up overriden variable

- pypdf/_page.py
- tests/test_page.py
> BUG: _get_fonts not processing properly CIDFonts and annotations

- make_release.py
> DEV: Give attribution in release notes

- pypdf/_page.py
- pypdf/_utils.py
- pypdf/generic/_data_structures.py
- tests/test_writer.py
This fixes the issue spotted in #2191
The solution was to re-introduce calls to `PageObject._push_pop_gs()`,
in `PageObject._merge_page` & `PageObject._merge_page_writer()`,
but to optimize `PageObject._push_pop_gs()` by introducing a `ContentsStream.isolate_graphics_state()` method.
> BUG: Fix test_watermarking_reportlab_rendering()

- docs/user/viewer-preferences.md
Fix a couple typos and add an explanatory comment to my recently written documentation.
> DOC: Fix typos and add a paragraph to ViewerPreferences docs.

- tests/test_filters.py
There have been two issues with the existing test:
* The name was incorrect, as it never really checked ImageMagick stuff.
* Running `from pypdf import _xobj_image_helpers` beforehand, for example because of other tests, would lead to "strange" failures due to Python not re-importing modules which already have been imported.
> DEV: Stabilize Pillow test with Pillow missing

- pypdf/_xobj_image_helpers.py
- tests/test_filters.py
This adds handling for nested color spaces for the `/DeviceN` color space.
Fixes #2240
> BUG: Fix nested /DeviceN color space

- README.md
Added link to CONTRIBUTING.md in the "Contributions" section and added three common questions and answers in the Q&A section.
> DOC: Link to CONTRIBUTING.md in README.md

- pypdf/generic/_data_structures.py
- tests/test_reader.py
> ROB: XYZ destination to cope with missing left and top param

- pypdf/_xobj_image_helpers.py
- tests/test_xobject_image_helpers.py
Previously, retrieving the image mode could lead to an infinite loop when nested color spaces have been used ("RecursionError: maximum recursion depth exceeded in comparison"). This has been fixed by limiting the default depth which is allowed.
>  BUG: Avoid exceeding recursion depth when retrieving image mode

- make_release.py
Retrieve the user logins for all commits from the GitHub API to correctly attribute each user, while trying to keep the number of API requests low to not hit the rate limits. Fixes #2245.
> DEV: Attribute correct authors in the release notes

- pypdf/_utils.py
I'm using pypdf in a project configured with pyright and the [`reportUnknownMemberType`](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportUnknownMemberType) option enabled. Since `IO` is not annotated explicitly with `Any` the error is triggered when using the `append` method of `PdfWriter`. This should probably also be fixed in pyright, but I thought the change here would be less controversial.
> MAINT: Explicitly provide Any for IO generic argument

- pypdf/_writer.py
> BUG: Error when filling a value with parentheses #2268

- pypdf/_xobj_image_helpers.py
- tests/test_filters.py
> BUG: Correctly handle image mode 1 with FlateDecode

- .github/workflows/github-ci.yaml
As proposed in https://github.com/py-pdf/pypdf/pull/2249#issuecomment-1774096819, this enables testing of Python 3.7 with and without encryption support. Previously, Python 3.7 would only run without encryption support.
> DEV: Test Python 3.7 with cryptopgraphy provider as well

- pypdf/generic/_data_structures.py
Use a visited memo to check if the current object in the clone operation has already been visited, and if so, do not add it to the list of objects. This avoids infinite recursion in case there are references to identical objects inside a PDF.
Unfortunately, since the example PDF contains financial data from a client I'm not free to provide the failing example that caused this PR. If you have a suggestion on how to remove that data while keeping the references identical, I'd be more than happy to contribute that. I hope the implementation is logical enough so this isn't needed.
The code that fails is as simple as:
```python
from pypdf import PdfReader, PdfWriter
reader = PdfReader('/path/to/sensitive/file.pdf')
writer = PdfWriter('myfilename.pdf', clone_from=reader)
```
> BUG: Infinite recursion when using PdfWriter(clone_from=reader)

- pypdf/_reader.py
This is done to prevent dictionary key error below when states are not initialized
> ROB: Initialize states array with an empty value

- pypdf/_cmap.py
> ROB: MissingWidth is IndirectObject

- docs/user/extract-attachments.md
The example code in `extract-attachments.md` iterates over a dictionary but doesn't properly call `.items()`, so the code fails as written. This adds the `.items()` call so the example works if cut and pasted into python.
> DOC: Fix typo in example in extract-attachments.md

- pypdf/filters.py
Fix a typo which seems to have been introduced by copying the docstring.
> DOC: Fix docstring for RunLengthDecode.decode

- pypdf/_cmap.py
- tests/test_cmap.py
Fixes the issue https://github.com/py-pdf/pypdf/issues/2290
> BUG: check words length in _cmap type1_alternative function

- pypdf/filters.py
While doing some error analysis, I stumbled upon the following error:
```
[...]
if CCITT.COLUMNS in parameters:
TypeError: argument of type 'IndirectObject' is not iterable
```
This resolves the error. Unfortunately, I do not have any public test document at the moment which I could share here or privately.
> BUG: Handle indirect objects as parameters for CCITTFaxDecode

- pypdf/_xobj_image_helpers.py
- pypdf/filters.py
- tests/test_images.py
> BUG: Cope with deflated images with CMYK Black Only

- pypdf/generic/_data_structures.py
This fixes a small typo. As this function is a nested one, this does not affect end users.
> STY: Fix typo "steam" -> "stream"

- pypdf/_reader.py
Calling _build_destination with a dictionary can cause it to error if the code which slices the array is executed. This skips the scenario where DictionaryObject does not have a "/D" key and is currently passed to _build_destination.
> ROB: Let _build_destination skip in case of missing /D key

- pypdf/_text_extraction/__init__.py
> ROB: Out-of-bounds issue in handle_tj (text extraction)

- .github/workflows/github-ci.yaml
This is a general fix which covers #2344, #2345 and #2350, including some incompatible changes as detailed in https://github.com/py-pdf/pypdf/pull/2344#issuecomment-1859671837.
The key point is that both actions have to be updated at the same time to avoid conflicts. Additionally, artifacts of the same name are not supported anymore, thus I decided to go the recommended route from https://github.com/actions/upload-artifact?tab=readme-ov-file#not-uploading-to-the-same-artifact to include the matrix parameters inside the artifact names.
> MAINT: Update upload-artifact and download-artifact actions from v3 to v4

- docs/user/adding-pdf-annotations.md
Fix example for Add the Highlight:
the `pypdf.annotations.Highlight` requires `rect` and `quad_points` as input parameters not `vertices`
> DOC: Correct the example of adding highlight annotation

- pypdf/filters.py
Previously, we might pass `"4bits"` as image mode to *Pillow*, leading to "unrecognized image mode". Example: `lfilters = IndirectObject(26, 0, 139771595681120)`, whose `get_object()` would yield `['/FlateDecode']` (going into the `else` branch of the filter handling until now).
While I have a corresponding document where I stumbled upon this error, I cannot disclose it due to privacy reasons.
> BUG: Handle IndirectObject as image filter

- docs/user/add-watermark.md
See https://github.com/py-pdf/pypdf/pull/1945
> DOC: Stamp images directly on a PDF

- docs/user/add-watermark.md
See https://patch-diff.githubusercontent.com/raw/py-pdf/pypdf/pull/1945
> DOC: Fix stamping example

- pypdf/_writer.py
See https://github.com/py-pdf/pypdf/pull/2003
> STY: Add PdfWriter._ID attribute

- tests/example_files.yaml
- tests/test_text_extraction.py
> TST: Add xfail test for #2336

- pypdf/__init__.py
- pypdf/_merger.py
- pypdf/_page.py
- pypdf/_reader.py
- pypdf/_utils.py
- pypdf/_writer.py
- pypdf/generic/__init__.py
- pypdf/generic/_base.py
- pypdf/generic/_data_structures.py
- pypdf/generic/_outline.py
- pypdf/generic/_rectangle.py
- pypdf/xmp.py
- tests/bench.py
- tests/test_merger.py
- tests/test_page.py
- tests/test_reader.py
- tests/test_utils.py
- tests/test_workflows.py
- tests/test_writer.py
Also don't use a default for the deprecation functions. If the version is mentioned explicitly with every call, we can more easily search for it.
* Bookmarks: `Consistent terminology for outline items` (#1156, pypdf==2.9.0) introduced it. Meaning in pypdf==4.0.0 we can remove them :tada:
> DEP: Remove deprecated code

- pypdf/_reader.py
See
* https://ipython.readthedocs.io/en/stable/config/integrating.html#MyObject._repr_mimebundle_
* https://discourse.jupyter.org/t/what-are-include-exclude-parameter-in-repr-mimebundle-for/23125
> ENH: Add Jupyter Notebook integration for PdfReader

- index.html
I stumbled upon the GitHub Pages site by accident, which was still referencing PyPDF2 and redirecting to its docs. This appears to be wrong and has been fixed.
> DOC: Replace references and redirects to PyPDF2

- docs/dev/testing.md
When doing some tests today, *pypdf* would fail in lots of cases due to missing example files. Document that the developer is currently expected to download the test files beforehand.
> DOC: Fix testing prerequisites

- docs/conf.py
- docs/dev/pypdf-parsing.md
- docs/index.rst
- docs/modules/PageObject.rst
- docs/modules/PdfReader.rst
- docs/modules/PdfWriter.rst
- docs/modules/constants.rst
- docs/modules/errors.rst
- docs/modules/generic.rst
- pypdf/_page.py
- pypdf/_reader.py
- pypdf/_utils.py
- pypdf/_writer.py
- pypdf/generic/_base.py
This fixes #1941 by cleaning up wrong references and adding new docs. Some notes about this:
* Building the docs now works without prior package installation.
* The intersphinx mapping will now always use the objects of the Python version used for the docs build.
* The intersphinx mapping for *Pillow* has been added.
* Links to private methods in the developer docs have been replaced by inline code as they are not part of the Sphinx docs.
* Some broken/outdated/strange docstrings have been fixed.
* New classes have been added to the docs. Module-specific classes have been added to the modules where they are being used directly, some generic classes/modules have been put into new files/pages.
* We have to exclude some members to avoid duplicate definitions.
Current output:
```
(venv) …
```
> DOC: Resolve build warnings

- tests/bench.py
- tests/test_writer.py
The tests tended to be unstable due to parallel access to the same file inside the working directory. This PR attempts to fix this by using temporary files instead.
> DEV: Write to temporary files instead of the working directory

- pypdf/xmp.py
Remove pending deprecations for version 4 discovered for the XMP support when working on #2380.
> DEP: Remove remaining XMP deprecations for version 4

- pypdf/_cmap.py
This adds support for the GBK2K-H and GBK2K-V cmaps mentioned in #2356 where I stumbled upon directly.
I do not consider #2356 solved with this for now as it is not clear to me why we do not add the complete mapping once and how to get nice test data. For now, I unfortunately have private test data only.
> BUG: Add support for GBK2K cmaps

- docs/user/suppress-warnings.md
- pypdf/_cmap.py
- pypdf/_utils.py
- tests/test_cmap.py
> MAINT: Replace warning with logging.error

- resources/multicolumn-lorem-ipsum.txt
- tests/test_workflows.py
> TST: Add test for layout extraction mode

- tests/test_writer.py
Issue in testssdue to missing closure of temporary files
closes #2394
> TST: Fix  side effect #2379

- pypdf/_reader.py
I've noticed this while going over #2391.
It's a minor cleanup, before we deprecate it in favor of a property exposing an int flag like this:
```
>>> UserAccessPermissions(15)
<UserAccessPermissions.MODIFY|PRINT|R2|R1: 15>
```
Then we would return a better datastructure + we could expose this as a property with which users could interact in a clearer way.
> STY: Use the UserAccessPermissions enum

- pypdf/_page.py
- pypdf/_reader.py
- tests/test_page.py
- tests/test_reader.py
If a page is not attached to a document, it does not have a page number. So we cannot return a "normal" number.
Before this PR, we returned -1.
Returning None compared to using `-1` has two advantages:
* It makes intuitive sense what it means
* It is part of the type annotation and mypy will complain about it if you don't handle that. If the callers (users) of pypdf are not careful, mypy might catch their error.
For this reason, we now return `None`.
See https://github.com/py-pdf/pypdf/discussions/2010
Closes #2371
> MAINT: Return None instead of -1 when page is not attached

- tests/test_writer.py
Improvement for #2379 to use a common method and appropriately close the temporary files. Fixes #2394.
> TST: Correctly close temporary files

- pypdf/_writer.py
BUG:  /TYPE for a link should be "/Annot" not "/Annots"   This change makes add_uri work;  previously, it did not.  
```python
writer = pypdf.PdfWriter()
writer.add_blank_page(width=500, height=500)
writer.add_uri(0, 'https://cnn.com', [0, 0, 499, 499])
print ('writing demo.pdf')
writer.write('demo.pdf')
```
> BUG: PdfWriter.add_uri was setting the wrong type

- .github/workflows/github-ci.yaml
- docs/modules/constants.rst
This adds a code style check to avoid unexpectedly shipping docs/docstrings which cause issues.
Options (the long names are only part of the upcoming 7.3 release), based upon https://www.sphinx-doc.org/en/master/man/sphinx-build.html:
* `-n`: Report warnings for missing references.
* `-W`: Turn warnings into errors and stop at first violation.
* `--keep-going`: Improve `-W` by collecting all violations and only failing at the end.
* `-T`: Display the full traceback on actual errors.
* `-b html`: Build HTML pages.
* `docs`: Source directory.
* `build/sphinx/html`: Target directory.
Fixes #2402.
> DEV: Fail on Sphinx issues

- pypdf/_page.py
- pypdf/_text_extraction/_layout_mode/_fixed_width_page.py
For fonts without an explicitly defined width for the " " character, it's still possible to generate a ZeroDivisionError when compiling TextStateParams objects in _fixed_width_page.recurs_to_target_op() if the font size or the Tz parameter has been set to 0. 
Discovered during processing of a "pre-OCR'd" image PDF having `{"/BaseFont": "/GlyphLessFont"}`.
Remove duplicate docstring for layout_mode_strip_rotated
> BUG: layout mode text extraction ZeroDivisionError

- tests/test_page.py
- tests/test_writer.py
The Debian ecosystem installs only packages which are also present in the Debian ecosystem for testing. This includes pytest, but it does not include fpdf2.
Adding the line 'pytest.importorskip("fpdf")' within the test and before the import ensures that pytest skips the test in case fpdf is not installed.
Closes #2408
> TST: Skip tests using fpdf2 if it's not installed

- tests/test_reader.py
Fix compatibility with `pytest==8`. Resolves #2427.
Relevant upstream change: https://github.com/pytest-dev/pytest/issues/9288
> TST: Avoid catching not emitted warnings

- pypdf/generic/_base.py
- tests/test_generic.py
Issue: https://github.com/py-pdf/pypdf/issues/2434
In the function encode_pdfdocencoding, cast its return value from bytearray to bytes to match its function signature.
This casting is necessary because bytearray is duck type compatible with bytes in mypy, however this library expects only bytes in its Encryption class.
> BUG: encode_pdfdocencoding() always returns bytes

- pypdf/_utils.py
- pypdf/generic/_base.py
- tests/test_generic.py
- tests/test_writer.py
alternative solution to #2460
fixes #2287
> ENH: automatic  access to pointed object

- make_release.py
- tests/scripts/data/commits__version_4_0_1.json
- tests/scripts/test_make_release.py
`make_release.py` did not correctly handle UTF-8 characters before, for example `→`, which was rendered as `\xe2\x86\x92`: https://github.com/py-pdf/pypdf/commit/cc306ad6abfb232f6922a7f0e939831d6611d0b7 and https://github.com/py-pdf/pypdf/releases/tag/4.0.2
The reason is that `str(b"abc")` yields the string representation `"b'abc'"` of the bytes type instead of the actual string value we want here. Properly decoding the bytes using `b"abc".decode()` does indeed yield the correct result `"abc"`.
The `lines` variable before
```
['"cc306ad6abfb232f6922a7f0e939831d6611d0b7:::REL: 4.0.2:::Martin Thoma"', '"b7bfd0d7eddfd0865a94cc9e7027df6596242cf7:::BUG: Use NumberObject for /Border elements of annotations (#2451):::rsinger417"', '"8cacb0fc8fee9920b0515d1289e6ee8191eb3f21:::DOC: Document easier …
```
> DEV: Fix changelog for UTF-8 characters

- docs/user/robustness.md
1. Remove mention of the deprecated PdfMerger.
2. Remove reference to the non-existent PdfWriter strict parameter.
> DOC: Amend robustness documentation

- tests/bench.py
The benchmarks are currently failing due to unclosed file descriptors and a metadata issue due to a wrong `NameObject`: https://github.com/py-pdf/pypdf/actions/runs/8069307746/job/22044079889
This PR resolves them.
> TST: Fix benchmark failures

- .github/workflows/github-ci.yaml
Version 2.0.0 has been released on 2022-06-01, thus the corresponding branch is useless as a CI target.
> MAINT: Remove reference to old 2.0.0 branch

- .github/ISSUE_TEMPLATE/feature-request.md
Assigning @MartinThoma to new feature requests does not make much sense without any active monitoring. I currently consider it sufficient enough to just handle feature requests in the same triaging workflow as bug reports - no need to explicitly assign someone as this will not speed up or slow down any processing at the moment.
> MAINT: Remove user assignment for feature requests

- docs/user/forms.md
- pypdf/_writer.py
- tests/test_writer.py
parse page/document annotations for orphan fields and reattach them to AcroForm/Fields closes #2453
> ENH: add reattach_fields function

- docs/user/file-size.md
Simplify the previous version and remove the side effect of changing the PDF in ways not just related to lossless compression (e.g. links on content page did not work in the created PDF).
> DOC: Improve lossless compression example

- pypdf/generic/_data_structures.py
- pyproject.toml
- tests/test_generic.py
add new capability required for other changes
> ENH: Add += and -= operators to ArrayObject

- .pre-commit-config.yaml
- docs/index.rst
1. Sort the API reference, de-emphasizing the deprecated PdfMerger.
2. Add new lines to .pre-commit-config.yaml.
> DOC: Minor readability increases

- pypdf/_writer.py
closes #2474
analysis in #2477
> BUG: Prevent recursive loop in some PDF files

- pypdf/_reader.py
- pypdf/_writer.py
- pypdf/generic/_data_structures.py
fixes #2523
situation met:
* length field is not correct
* xref may contains not ordered stream datas
* xref contains some free entries (i.e. not contains stream offset)
> ROB: Robustify stream object extraction

- docs/meta/faq.md
- pypdf/_reader.py
- pypdf/generic/_data_structures.py
> DOC: Update references and formatting

- docs/user/reading-pdf-annotations.md
Copied in order from Table 171 annotation types of the PDF 2.0 Specification. The three added annotations are Redact (PDF 1.7), Projection (PDF 2.0) and RichMedia (PDF 2.0).
> DOC: Update annotation list

- .readthedocs.yaml
Using ubuntu-lts-latest may break your builds unexpectedly if your project isn’t compatible with the newest Ubuntu LTS version when it’s updated by Read the Docs. [https://docs.readthedocs.io/en/stable/config-file/v2.html#build-os]. For us this may be a feature since compatibility with the latest Ubuntu LTS is desirable and is in effect an extra test.
> MAINT: Update Read the Docs configuration

- pypdf/_reader.py
- pypdf/_writer.py
- tests/test_reader.py
closes #2516
cope with cases where the xref entries do not point to valid headers
> ROB: Rebuild xref table if one entry is invalid

- pypdf/_page.py
- pypdf/_writer.py
- pypdf/constants.py
- pypdf/generic/_data_structures.py
> MAINT: Ressources → Resources (and internal name childs)

- .github/scripts/check_pr_title.py
> DEV: Add REL to known PR prefixes

- pypdf/_page.py
- tests/test_workflows.py
> BUG: Extract text in layout mode without finding resources

- pypdf/_page_labels.py
Maintaining/validating example images inside a PR is complicated. Rather use the existing issue #2560 if there are new findings.
> DEV: Remove page labels PR link from message

- pypdf/_writer.py
- pypdf/generic/_data_structures.py
- tests/test_writer.py
closes #2234
closes #2512
replaces  #2333
> BUG: Fix fields update where annotations are kids of field

- requirements/ci.in
We have migrated from `flake8` to `ruff` and thus do not need to maintain the `flake8` dependencies anymore.
`types-dataclasses` is the accompanying package of `dataclasses`, only providing backports for Python < 3.7 which we dropped already: https://pypi.org/project/types-dataclasses/
> DEV: Remove unused dependencies

- pypdf/_reader.py
- tests/test_reader.py
> ROB: Tolerate "truncated" xref

- pypdf/generic/_base.py
- tests/test_generic.py
> ENH: Allow multiple charsets for NameObject.read_from_stream

- tests/__init__.py
- tests/test_filters.py
- tests/test_workflows.py
Prepare support for `Pillow>10.3.0` by allowing truncated images to be loaded. Partial fix for #2568.
> TST: Allow loading truncated images if required

- pypdf/generic/_data_structures.py
- tests/test_page.py
Fixes https://github.com/py-pdf/pypdf/issues/2587
> BUG: Fix merge_page sometimes generating unknown operator 'QQ'

- pypdf/_xobj_image_helpers.py
- pypdf/filters.py
- tests/test_images.py
closes #2343:
1st case : image with images in 1 byte encoding with Separation colorspace
2nd case: similar + \n to be ignored at the end of the image data
> ROB: Cope with some image extraction issues

- pypdf/_xobj_image_helpers.py
- pypdf/filters.py
- tests/test_images.py
> ROB: Cope with some issues in pillow

- .github/workflows/create-github-release.yaml
- .github/workflows/publish-to-pypi.yaml
Fixes #2596 which led to always executing (and failing) the secondary workflows for a release.
> DEV: Only run further release steps on tagging

- docs/dev/pypdf-writing.md
- docs/meta/project-governance.md
- pypdf/_writer.py
Most of them were found by `codespell` and `typos`.
> DOC: Fix some typos in documentation

- docs/user/file-size.md
The example failed when a PDF file did not contain any metadata.
> DOC: Make code example more robust

- pypdf/_writer.py
- tests/test_writer.py
> ROB: discard /I in choice fields for compatibility with acrobat

- pypdf/_reader.py
- tests/test_reader.py
> BUG: Fix UnboundLocalError on malformed pdf

- pypdf/annotations/_markup_annotations.py
- pypdf/generic/__init__.py
- tests/test_generic.py
Currently, pypdf does not set annotation flags when highlighting text. The flag at bit 3 needs to be set in order to print highlighted text.
> BUG: Highlighted Text Cannot Be Printed

- pypdf/filters.py
- tests/bench.py
- tests/test_images.py
> BUG: Reading large compressed images takes huge time to process

- pypdf/_doc_common.py
- tests/test_reader.py
> ROB: cope with loops in Fields tree

- pypdf/_reader.py
- pypdf/_writer.py
Plus tiny documentation changes
> STY: Move is_encrypted below __init__

- tests/test_page.py
- tests/test_reader.py
Fixes #2428 
Imho, the test does too many things. Thus, instead of replacing with e.g. `txt_file_path fixture`, I removed things:
- write to file: The written file is never used. What was the reason to add it here in this test? -> Update: added back with `tmp_path`
- TypeError: does not seem to fit into this test -> Update: new test in test_page.py
> TST: simplify test_get_images

- pypdf/_reader.py
- tests/test_reader.py
> ENH: context manager for pdfreader

- pypdf/types.py
Also reordered FitType and AnnotationSubtype to be in the same order as tabled in ISO 32000-2:2020 (PDF 2.0).
> MAINT: Update AnnotationSubtype

- pypdf/_writer.py
CatalogDictionary is imported twice, with one of them is a rename: "from .constants import CatalogDictionary as CD". Removed this as "CD" is only used once.
> STY: Within PdfWriter name CatalogDictionary consistently

- pypdf/_writer.py
- pypdf/_xobj_image_helpers.py
- pypdf/generic/_base.py
- pypdf/generic/_utils.py
- tests/test_generic.py
- tests/test_images.py
> BUG: Fix images issue 4 bits encoding and LUT starting with UTF16_BOM

- docs/dev/cmaps.md
- docs/user/add-watermark.md
- docs/user/adding-pdf-annotations.md
- docs/user/cropping-and-transforming.md
- docs/user/forms.md
- pypdf/_writer.py
Including sorting imports of Python examples
> DOC: Small improvements to Markdown files

- pypdf/_utils.py
- pypdf/constants.py
- tests/test_utils.py
> BUG: Fix deprecation for Ressources when using old constants

- pypdf/_writer.py
- tests/test_writer.py
closes #2670
in alternative to #2671
> ROB: cope with missing Standard 14 fonts in fields

- docs/user/extract-images.md
- pypdf/generic/_data_structures.py
- tests/test_images.py
> ENH: add decode_as_image() to ContentStreams

- docs/conf.py
- pypdf/_reader.py
- pypdf/_writer.py
- pypdf/generic/_base.py
- pypdf/generic/_data_structures.py
- pypdf/generic/_utils.py
- pypdf/xmp.py
Remove two spaces after a period so everywhere one space is used. Also, in _writer.py initialize PA.KIDS before PA.COUNT to match PDF specification table order.
> STY: Consistency of spaces after period

- pypdf/_cmap.py
- tests/test_cmap.py
> ENH: accepts ETen-B5 and UniCNS-UTF16 encodings

- docs/user/metadata.md
- pypdf/_writer.py
- pypdf/xmp.py
Remove a superfluous PdfReader in an import clause.
> DOC: Tiny changes

- pypdf/_writer.py
- tests/test_writer.py
> ROB: cope with fields with upside down box/rectangle

- tests/test_utils.py
Second argument of test_b changed from str to bytes.
> STY: Change argument type

- pypdf/_writer.py
- tests/test_writer.py
> BUG: Cope with Matrix entry in field annotations

- pypdf/_crypt_providers/_cryptography.py
See https://github.com/py-pdf/pypdf/pull/2764 - ci failed due to 
> cryptography.utils.CryptographyDeprecationWarning: ARC4 has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.ARC4 and will be removed from this module in 48.0.0.
> MAINT: Deal with cryptography>=43 moving ARC4

- pypdf/_utils.py
> STY: Amend B_CACHE key types

- pypdf/filters.py
Add comments and tiny refactor.
> STY: Increase readability

- .github/workflows/github-ci.yaml
- requirements/ci-3.11.txt
Let's start testing against Python 3.13, which is soon to be planned to have its first release candidate. Prior testing has shown that the latest dependencies work fine, let's see if our pinned dependencies are recent enough.
> DEV: Test against Python 3.13

- CONTRIBUTORS.md
- pypdf/_xobj_image_helpers.py
- pypdf/errors.py
- tests/test_xobject_image_helpers.py
When extracting an image that contains no data, a `ZeroDivisionError` is thrown in the except block of the `_extended_image_frombytes` method.
This PR adds a check for that specific situation and raises a ValueError when it arises.
> ROB: Handle images with empty data when processing an image from bytes

- .github/workflows/release.yaml
Hi! I'm Diogo from Google's Open Source Security Team([GOSST](https://opensource.googleblog.com/2023/04/googles-open-source-security-upstream-team-one-year-later.html)) and I'm dropping by to suggest this small change that will enhance the security of your repository by preventing script injection attacks through your GitHub workflows.
In the piece of code I changed, you were directly using the value of a variable that comes from a user's input, so a malicious user could exploit that input and use it to run arbitrary code. By using an intermediate environment variable, the value of the expression is stored in memory, used as a variable and doesn't interact with the script generation process. This mitigates the script injection risks and also keeps your workflow running exactly as before. …
> SEC: fix github workflow vulnerable to script injection

- pypdf/annotations/_non_markup_annotations.py
Also remove unused DEFAULT_ANNOTATION_FLAG.
> STY: Small readability increases

- pypdf/_utils.py
Comment courtesy of @shartzog, issue #2726.
> STY: Refactor b_

- .github/workflows/github-ci.yaml
- pypdf/_page.py
- pypdf/_protocols.py
- pypdf/_text_extraction/_layout_mode/_fixed_width_page.py
- pypdf/_xobj_image_helpers.py
- pypdf/types.py
remove support to python 3.7
as discussed in #2418
> MAINT: drop Python 3.7 support

- pypdf/_doc_common.py
- pypdf/_reader.py
- tests/test_reader.py
> ENH: report PdfReadError instead of RecursionError

- pypdf/_xobj_image_helpers.py
- tests/test_images.py
- tests/test_workflows.py
> BUG: fix sheared image

- pypdf/generic/_base.py
- pypdf/generic/_utils.py
- tests/test_generic.py
- tests/test_writer.py
> ENH: accept utf strings for metadata

- pypdf/_reader.py
- tests/example_files.yaml
- tests/test_reader.py
remove _get_page from reader which is redundant with get_page
faced again some issues with a broken link from tika. Replace them with github links.
> MAINT: remove unused code

- pypdf/_reader.py
- tests/test_reader.py
Fixes #2806.
When running the same code as described in #2806 with the same PDF, now this happens:
```python
>>> list(reader.pages)
Object 493 0 not defined.
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/pypdf/pypdf/_page.py", line 2356, in __len__
return self.length_function()
^^^^^^^^^^^^^^^^^^^^^^
File "/pypdf/pypdf/_doc_common.py", line 352, in get_num_pages
self._flatten()
File "/pypdf/pypdf/_doc_common.py", line 1100, in _flatten
catalog = self.root_object
^^^^^^^^^^^^^^^^
File "/pypdf/pypdf/_reader.py", line 195, in root_object
raise PdfReadError('Cannot find "/Root" key in trailer')
pypdf.errors.PdfReadError: Cannot find "/Root" key in trailer
```
> ROB: Raise PdfReadError when missing /Root in trailer.

- pypdf/_page.py
- tests/test_workflows.py
> ENH: Robustify on missing font for Tf  operator in text_extract()

- pypdf/_cmap.py
- tests/test_cmap.py
> ENH: add UniGB-UTF16 encodings

- pypdf/generic/_data_structures.py
- tests/test_generic.py
cope with objects where the filter is ["/FlateDecode"] and/or which data has not been read yet
> ROB: robustify .set_data()

- pypdf/papersizes.py
- pypdf/xmp.py
> DOC: Small changes to PaperSize notes

- pypdf/_page.py
- tests/test_text_extraction.py
visitor* function arguments are silently ignored when extraction_mode="layout".  Document this a bit better and add a warning when these arguments are ignored.
Closes #2840
> BUG: Warn when visitor* arguments are ignored

- tests/test_filters.py
test_image_without_pillow runs a generated script which causes the Python path to exclude the current directory.  The generated script tries to import pypdf and either cannot find it or it finds the version in pyenv instead of the version being tested.  Add "." to PYTHONPATH so the correct version of pypdf is used.
Closes #2849
> BUG: test_image_without_pillow cannot find pypdf

- pypdf/_reader.py
- tests/test_reader.py
> BUG: tolerate truncated files and no warning when jumping startxref

- pypdf/_utils.py
- pypdf/generic/_data_structures.py
- tests/test_reader.py
> ROB: tolerate comments in arrays

- pypdf/_doc_common.py
- pypdf/_writer.py
- tests/test_writer.py
> ROB: merge documents with named destinations  with invalid page

- pypdf/filters.py
These are the same as the next line exception messages. Also fix one typo.
> STY: Remove duplicated comments

- pypdf/_writer.py
`_update_field_annotation` is still way too long, but it got a bit better :smile:
> MAINT: Refactor _update_field_annotation and _get_clone_from

- pypdf/_xobj_image_helpers.py
- pypdf/constants.py
- pypdf/filters.py
* Create _apply_decode and move it to _xobj_image_helpers
* Create _get_mode_and_invert_color and move it to _xobj_image_helpers
* Create _apply_alpha as an inner function as it's calling _xobj_to_image
This reduced the Cyclomatic Complexity from 44 to 19
> STY: Refactor _xobj_to_image

- pypdf/_cmap.py
- tests/test_cmap.py
> BUG: cope with encoding with too many differences

- pypdf/generic/_data_structures.py
- tests/test_reader.py
> BUG: Cope with unbalanced delimiters in dictionary object

- pypdf/_doc_common.py
- pypdf/_reader.py
- pypdf/generic/_base.py
- tests/test_reader.py
> ROB: Repair pdf with invalid Root object

- pypdf/_codecs/_codecs.py
- pypdf/filters.py
- tests/test_codecs.py
- tests/test_filters.py
The basis for this implementation is https://github.com/empira/PDFsharp/blob/master/src/foundation/src/PDFsharp/src/PdfSharp/Pdf.Filters/LzwDecode.cs (MIT licensed)
As this removes the `LZWDecode` class from a public module, we have to do a major release when we release this change.
> MAINT: New LZW decoding implementation

- pypdf/_page.py
- tests/test_text_extraction.py
Close #2262
Due to file copyright issues, I found a similar file in RESOURCE.
As far as I can confirm, there seem to be other problems with the file output, but I think there are no problems when checking this issue.
> BUG: Line breaks are not generated due to incorrect calculation at the text leading

- pypdf/_cmap.py
- pypdf/_page.py
I made changes to separate the part that gets the space code from the part that analyzes it for clarity. I hope you like it.
I was wondering about the space_code determination for type1_alternative.
Perhaps the comparison of the if statement itself is not being used, as I think the content is inadequate.
```
if words[2].decode() == b" ":
space_code = i
```
> MAINT: Generalize the method of obtaining space_code

- pypdf/_writer.py
- tests/test_writer.py
Also some documentation tweaks.
> STY: Modify error messages in PdfWriter

- pypdf/_xobj_image_helpers.py
- tests/test_xobject_image_helpers.py
> ROB: Soft failure for flate encode image mode 1 with wrong LUT size

- pypdf/_page.py
- pypdf/_text_extraction/_layout_mode/_fixed_width_page.py
- resources/crazyones_layout_vertical_space.txt
- resources/crazyones_layout_vertical_space_font_height_weight.txt
- tests/test_text_extraction.py
Implements feature proposed in issue #2915
> ENH: Add ``layout_mode_font_height_weight`` argument to ``PageObject.extract_text()``

- pypdf/generic/_data_structures.py
- tests/test_generic.py
Found some PDFs in the wild where instantiating a PdfReader object would fail due to an infinite loop regarding this case.
The PDFs themselves were corrupted. Other programs I tested them with such as Mac Preview and poppler pdftotext would error out. But it would be best to not infinite loop and use up all system memory when attempting to load them.
> ROB: Fix infinite loop case when reading null objects within an Array

- pypdf/_doc_common.py
- tests/test_reader.py
This missing entry was spotted while exposing metadata in https://github.com/py-pdf/pdfly/pull/73
> ENH: Adding support for reading .metadata.keywords

- CONTRIBUTORS.md
- pypdf/_page.py
- pypdf/generic/_data_structures.py
Fixes https://github.com/py-pdf/pypdf/pull/2792#discussion_r1837246804.
> MAINT: Narrow return type for `ContentStream.operations`

- pypdf/_utils.py
deprecate_with_replacement and deprecate_no_replacement are not raising exceptions, but are issuing warnings. Change their docstrings to reflect this.
> DOC: Improve two docstrings

- pypdf/_doc_common.py
- tests/test_reader.py
This was deprecated, with replacement user_access_permissions. Removal was scheduled for version 5.0.0 or later.
> DEP: Amend decode_permissions

- pypdf/_doc_common.py
- tests/test_reader.py
Undo PR: 92bb037dba0b8c3149c8b06c133fbc632a3eb6a0
According to our deprecation policy, we would have to issue a new major release for that change.
> MAINT: Revert 92bb037

- pypdf/_writer.py
- tests/test_writer.py
Some PDFs happen `dest["/Page"]` is none which causes 
`AttributeError: 'NoneType' object has no attribute 'indirect_reference'`
in the following code
> ROB: Skip destination page being None in PdfWriter

- pypdf/_writer.py
- tests/test_writer.py
> ROB: Skip annotation destination being NullObject in PdfWriter

- pypdf/_encryption.py
> STY: Change if to elif

- pypdf/_cmap.py
- pypdf/_page.py
- tests/test_cmap.py
Closes #2966 
This handles indirect objects when calculating font widths
> BUG: Handle indirect objects in font width calculations

- pypdf/_writer.py
- pypdf/generic/_base.py
- tests/test_generic.py
based on comments from #2949 
- Fixing reference of value with str.__new__ output
- updated type annotation on update_page_form_field_values
> BUG: Fixed reference of value with str.__new__ in TextStringObject

- pypdf/_writer.py
Put as the last member of PdfWriter, as is different functionality to the other methods.
> STY: Move _repr_mimebundle_

- pypdf/_writer.py
> STY: Slight refactor of remove_images

- pypdf/_writer.py
Make the names of annotation variables more consistent and readable.
> STY: Rename local annotation variables

- docs/dev/pdf-format.md
- pypdf/constants.py
Move from constants.py to pdf-format.md, a more natural location.
> DOC: Move PDF specification links

- pypdf/_doc_common.py
- pypdf/_reader.py
Put integration into Jupyter Notebooks at end of classes PdfDocCommon and PdfReader as is functionally different from the other methods.
> STY: Put Jupyter functionality at end of class

- pypdf/_page.py
- pypdf/generic/_data_structures.py
- pypdf/generic/_image_inline.py
- tests/test_writer.py
This PR fixes a regression introduced in version 4.3.0 which would always try to extract inline images twice due to setting the wrong input stream position. The corresponding behavior is not directly obvious and only becomes visible with some PDF files as the one used in the test, where the faulty change would silently drop a `Q` operator and thus basically destroy the remaining layout of the PDF file.
During analysis, I have added some basic comments and fixed a faulty error message I stumbled upon as well.
Fixes #2927.
> BUG: Avoid extracting inline images twice and dropping other operators

- pypdf/_cmap.py
- tests/test_cmap.py
> ROB: Ignore odd-length strings when processing cmap lines

- pypdf/filters.py
- tests/test_filters.py
> ROB: Fall back to non-Adobe Ascii85 format for missing end markers

- pypdf/_xobj_image_helpers.py
PEP 289 – Generator Expressions.
> STY: Use generator expressions

- pypdf/_page.py
- tests/test_text_extraction.py
> ROB: Gracefully handle some text operators when the operands are missing

- pypdf/filters.py
- pypdf/generic/_base.py
- tests/test_filters.py
Additionally, use a *dataclass* for the parameter to simplify debugging.
> BUG: Handle IndirectObject in CCITTFaxDecode filter

- pypdf/filters.py
- tests/test_filters.py
Deprecate CCITParameters with replacement CCITTParameters.
> DEP: Deprecate with replacement CCITParameters

- docs/user/adding-pdf-annotations.md
> DOC: Add note about default line colors

- tests/test_workflows.py
Replacing a whitespace character with the empty string is done by strip() in the next line.
> STY: Remove replace function

- tests/example_files.yaml
- tests/test_generic.py
- tests/test_merger.py
- tests/test_page.py
- tests/test_reader.py
- tests/test_workflows.py
- tests/test_writer.py
- tests/test_xmp.py
Relates to #3035. Alternative to #3038.
> TST: Replace broken Apache Tika Corpora urls

- pypdf/_writer.py
- tests/test_writer.py
The `assert isinstance` hid the information that `_info` is `Optional`, in which case `add_metadata` would raise an assertion error.
Properly initialise `_info` if it's not set.
Fixes #3036
> BUG: Ensure `add_metadata` can deal with `_info = None`

- tests/test_writer.py
Tests started to fail on Ubuntu 24.04 due to using a too large threshold.
Valid cases now have 0.9999915926764715 and invalid ones 0.9993737673623087.
> TST: Fix image similarity for upcoming Ubuntu 24.04

- pypdf/_reader.py
Move from method _initialize_stream to __init__, where other xref-related initialization occurs.
> STY: Move self._startxref initialization

- pypdf/_crypt_providers/_fallback.py
- pypdf/_encryption.py
Use a generator expression within the bytes constructor, eliminating the need for the intermediate bytearray.
> STY: Remove use of intermediate bytearray

- pypdf/_utils.py
- tests/test_utils.py
Table 1—White-space characters; ISO 32000-2:2020 (PDF 2.0).
> STY: Add form feed to WHITESPACES

- pypdf/_xobj_image_helpers.py
- pyproject.toml
[tool.ruff.lint.pydocstyle]
convention = "google"
Append a colon, as pydocstyle found one section name should end with a colon.
> DEV: Add tool.ruff.lint.pydocstyle to pyproject.toml

- pypdf/_xobj_image_helpers.py
EncodedStreamObject and DecodedStreamObject are only used once within the same if statement as TextStringObject. For consistency import TextStringObject with these at the top of the file.
> STY: Import TextStringObject at the top of file

- pyproject.toml
PD011 is use ".to_numpy()" instead of ".values". Was unused.
> DEV: Remove PD011 from ignored Ruff rules

- tests/test_filters.py
- tests/test_generic.py
- tests/test_reader.py
Use `pytest.warns()` to assert for warnings, so that the test suite passes without `-Werror`.
> TST: Fix warning assertions to use `pytest.warns()`

- pypdf/_xobj_image_helpers.py
Make it obvious that "mode" is the new value of "prev_mode". Also change "by" to "byt" for better readability.
> STY: Change variable names

- tests/test_filters.py
Also remove an underscore from a test name, define bytes directly, and modify some comments.
> TST: Uncomment an assert

- pypdf/_page.py
Specifically CUSTOM_RTL_MIN, CUSTOM_RTL_MAX, and CUSTOM_RTL_SPECIAL_CHARS.
> MAINT: Remove unused variables

- pypdf/_page.py
Change comments, one "elif" to an "if", and one variable name.
> STY: Tweak function _extract_text

- pypdf/generic/_data_structures.py
- pyproject.toml
Move from tool.ruff.lint (global) to tool.ruff.lint.per-file-ignores. PLW3301: nested-min-max. Nested min and max calls can be flattened into a single call to improve readability.
> DEV: Move Ruff rule PLW3301

- pypdf/_writer.py
- tests/test_writer.py
> BUG: Handle annotations being None on merging

- .github/SECURITY.md
- docs/dev/releasing.md
- docs/meta/comparisons.md
- docs/meta/history.md
- docs/meta/project-governance.md
- docs/meta/taking-ownership.md
- docs/user/cropping-and-transforming.md
- pyproject.toml
> DOC: stefan6419846 becomes BDFL of pypdf

- pypdf/generic/_data_structures.py
- tests/test_images.py
When fixing the inline image extraction in #3002, the fallback behavior would break accidentally by leaving the stream before the EI marker. We never saw this due to the tests somehow being not strict enough, thus leading to the error
> b'EI' operator met whereas not expected, please share usecase with pypdf dev team
> BUG: Fix stream position on inline image fallback extraction

- pyproject.toml
Otherwise, building the package on local systems leads to sdists being 408 MB instead of 4.8 MB.
> DEV: Avoid bundling the PDF cache directory in sdists

- pypdf/_writer.py
- tests/test_forms.py
- tests/test_workflows.py
> BUG: Fix check box value which should be name object

- pyproject.toml
PLW0602: Using a global but no assignment is done.
> DEV: Remove Ruff rule PLW0602

- pypdf/_cmap.py
- tests/test_cmap.py
> ROB: Ignore non-numbers for width when building font width map

- pypdf/generic/_base.py
- tests/test_generic.py
> ENH: Add support for `IndirectObject.__contains__`

- pypdf/_reader.py
- tests/test_reader.py
> ROB: Raise proper error on infinite loop when reading objects

- pypdf/generic/_image_inline.py
- tests/generic/test_image_inline.py
> BUG: Fix detection of inline images followed by names or numbers

- pypdf/_reader.py
- tests/test_reader.py
> ROB: Consider root objects without catalog type as fallback

- pypdf/_page.py
- pypdf/_writer.py
- pypdf/generic/_base.py
- pypdf/pagerange.py
- pyproject.toml
- tests/test_page_labels.py
RUF005: Consider iterable unpacking instead of concatenation.
> STY: Remove excluding Ruff rule RUF005

- pypdf/_reader.py
Unnecessary assignment before a return  statement, and an unnecessary "else" after "return" statement.
> STY: Remove unnecessary code around return statements

- pyproject.toml
RET508: Unnecessary "else" after "break" statement.
> DEV: Remove excluded Ruff rule RET508

- pyproject.toml
PLW0603: Using the global statement to update is discouraged. Move from excluding in tool.ruff.lint to tool.ruff.lint.per-file-ignores (only place it is used).
> DEV: Move Ruff rule PLW0603

- docs/user/cropping-and-transforming.md
- pypdf/filters.py
- tests/test_filters.py
> BUG: Consider BlackIs1 parameter for CCITTFaxDecode filter

- pyproject.toml
D404: First word of the docstring should not be "This". D406: Section name should end with a newline.
> DEV: Remove ignore Ruff rules D404 and D406

- pypdf/_writer.py
- pyproject.toml
- tests/__init__.py
RET502: Do not implicitly "return None" in function able to return non-"None" value.
> DEV: Remove ignore Ruff rule RET502

- pypdf/_doc_common.py
Function previously, but no longer, raises a PdfReadError.
> DOC: Modify Raises section

- pypdf/_page.py
- tests/test_page.py
These issues were discovered while trying to extract text and images from some PDF files which were incomplete, but partially fixed.
> ROB: Handle some None values for broken PDF files

- pypdf/_page.py
- tests/test_text_extraction.py
Closes #3247 
Per the [PFD32000.book](https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/PDF32000_2008.pdf) 9.4.2, the `T*` is equivalent to `0 -TL TD`. This changes the pypdf implementation to be consistent.
> BUG: T* 2D Translation consistent with PDF 1.7 Spec

- pypdf/_doc_common.py
Also move flattened_pages to the beginning of the class with the other attributes.
> MAINT: Add to the explanation of _flatten

- pypdf/_writer.py
- tests/test_writer.py
Last month I contributed pull request https://github.com/py-pdf/pypdf/pull/3216, an enhancement to `PdfWriter.removeText()` that allows users to remove only the specified fonts. Since then, I've come across a few PDFs where my simple logic to find fonts wasn't working. This fix walks through the PDF structure to find font references more reliably. I also added a few explanatory comments.
> BUG: Get font information more reliably when removing text

- pypdf/_page.py
Remove a redundant comment and modify some other comments. Reorder page boundaries to familiar order.
> MAINT: Tweak class PageObject

- pypdf/_text_extraction/_layout_mode/_fixed_width_page.py
- tests/test_text_extraction.py
The loops ...
```python
for item in iterator:
...
```
... and ...
```python
while True:
try:
item = next(iterator)
except StopIteration:
break
....
```
... are functionally equivalent. Both consume the `next` value form an iterator and exit when the iterator raises a `StopIteration`. The `for` loop more intuitively represents the intent to iterate the `ops`, and improves clarity that the loop exits if there are no more ops. This also reduces the number of logical paths through the function(s), consolidate the flow control, and eliminates the need for large try/except blocks, which tent to have unintended consequences
Per copilot:
---
The changes in this pull request involve refactoring the code to replace `while True` loops with `for` loops and removing `try`/`except StopIteration` …
> STY: Idiomatic iteration in _fixed_width_page.py

- pypdf/filters.py
- tests/test_filters.py
If the filter encounters the EOD marker after reading an odd number of hexadecimal digits, it shall behave as if a 0 (zero) followed the last digit [PDF 2.0, §7.4.2].
> MAINT: Comform ASCIIHexDecode implementation to specification

- pypdf/_writer.py
- pypdf/generic/_base.py
- pypdf/generic/_data_structures.py
Use "mypy" in the second expression of the assert statement, instead of a comment explaining the assert statement is for mypy.
> STY: Standardize mypy assert statements

- pypdf/_text_extraction/_layout_mode/_fixed_width_page.py
The existing code for warning if there is rotated text or uninterpretable fonts is slightly overcomplicated. It follows two nested loops to decide if there is text to warn, and needs local variables to flag if a warning is already emitted. It also comingles debug-only logic with the operational code by re-checking for each group of operators if they will be debugged later.
This PR clarifies both by waiting until all operators are collected before searching them for warn-able data, or deciding if to debug them. This removes the need for several variables, nested loops, and several conditional expressions within the loop.
> STY: Simplify warnings & debugging in layout mode text extraction

- pypdf/_writer.py
- tests/test_writer.py
> ROB: Fix merging documents if there are no Dests

- pypdf/_writer.py
- tests/test_writer.py
> ROB: Allow merging when annotations miss D entry

- pypdf/generic/_base.py
- tests/test_generic.py
Per the spec, name objects cannot contain unescaped delimiters, which include angle, curly and square brackets (currently missing).
I've attached a sample input PDF with a valid, correctly escaped name object. When appending this to a new PdfWriter the output is invalid (incorrectly escaped):
```
>>> w = PdfWriter()
>>> w.append('nameobj.pdf')
>>> w.write('out.pdf')
```
[out.pdf](https://github.com/user-attachments/files/20173760/out.pdf)
[nameobj.pdf](https://github.com/user-attachments/files/20173761/nameobj.pdf)
> BUG: Add delimiters to NameObject.renumber_table

- pypdf/generic/_base.py
- tests/test_generic.py
The SOLIDUS is a prefix, so use this as the name.
> MAINT: Change name of class attribute

- pypdf/_cmap.py
- tests/test_cmap.py
> ROB: Handle NullObject for cmap encoding Differences entry

- pyproject.toml
- requirements/dev.txt
Migrate to PEP 639 license expressions.
Requires flit>=3.11: https://flit.pypa.io/en/stable/history.html#version-3-11
> DEV: Modernize license specifiers

- pypdf/_page.py
- pypdf/_text_extraction/_text_extractor.py
The goal of this PR is to increase maintainabilty by reducing the size of __page.py. This helps, because:
* The risk of merge conflicts decreases
* It becomes easier to see which kind of change is done
It also prepares for a big more complex refactoring (see https://github.com/py-pdf/pypdf/pull/3339 )
This PR is almost only copy-paste (moving the location of the code, but no additions/changes):
* The license preamble was added
* The new TextExtration class was added + used by _page.py
* `_get_actual_font_widths` and `_handle_tj` were only moved
> MAINT: Move code from _page.py to _text_extraction

- pypdf/__init__.py
- pypdf/_page.py
- pypdf/_text_extraction/_text_extractor.py
- tests/test_text_extraction.py
Move all non-local variables and nested functions from PageObject._extract_text()
to the TextExtraction class to improve code organization and maintainability.
Changes:
- Moved state variables (cm_matrix, tm_matrix, text, output, etc.) to TextExtraction instance variables
- Moved compute_str_widths() and process_operation() functions to TextExtraction methods
- Added initialize_extraction() method to set up extraction parameters
- Simplified _extract_text() to use TextExtraction instance instead of local state
- Maintains existing API and functionality while improving code structure
This refactoring eliminates the need for nonlocal variables and nested functions,
making the text extraction code more modular and easier to understand.
> MAINT: Move text extraction state to TextExtraction class

- docs/user/metadata.md
> DOC: Document how to read and modify XMP metadata

- pypdf/_writer.py
- pypdf/generic/_data_structures.py
- pypdf/xmp.py
- tests/test_xmp.py
Closes #3391.
According to table 29 of the PDF 2.0 specification, the Metadata stream inside the catalog dictionary should be an indirect reference. The old code would inline the content stream into the catalog dictionary, making the file unreadable in some applications like some versions of Adobe Acrobat.
> BUG: Fix XMP handling dropping indirect references

- .github/workflows/github-ci.yaml
- MANIFEST.in
- pyproject.toml
Checked that sdist contains CHANGELOG.md and LICENSE,
whereas the bdist contains just the LICENSE.
> DEV: Delete MANIFEST.in

- pypdf/_writer.py
In FIPS mode, md5 might be available and approved. It might also be
available, but only on opt-in basis for unapproved usage. And very
strict systems might not have md5 even on opt-in basis.
Python has API to expose this as "usedforsecurity=False" argument, see
python documentation.
The rolling document checksum is not used for cryptograpic protection,
but rather used out of convenience. Hence allow using MD5 on more FIPS
systems.
This is no effective change for regular non-fips python builds.
> ENH: Add support for python in FIPS mode for document identifier

- pypdf/_utils.py
- tests/test_utils.py
Resolves #3446 
As mentioned in #3446 you can test with [guwunmong.pdf](https://github.com/user-attachments/files/21969610/guwunmong.pdf).
```python
>>> import os
>>> from io import BytesIO
>>> from pypdf import PdfReader
>>> with open("guwunmong.pdf", "rb") as f:
...     pdf_bytes = f.read()
>>> reader = PdfReader(stream=BytesIO(pdf_bytes))
>>> metadata = reader.metadata
>>> creation_date = str(metadata.creation_date) if metadata.creation_date else None  # Used to raise IndexError here.
>>> creation_date
>>> print(creation_date)  # Prints None as expected.
None
```
> BUG: Guard empty input to prevent IndexError

- pypdf/_reader.py
- tests/test_reader.py
- tests/test_workflows.py
> ROB: Improve handling for malformed cross-reference tables
